### ISSUE TITLE
c++ 配置

### ISSUE THREAD

**Issue by dzhwinter** [zilongshanren/spacemacs-private#1]
我是昨天emacs群里 宁静的语言
c++配置里semantic部分用处是什么？  
 post init company 从comapny-backends里删除了semantic-backend了，这个配置的用处是？

**Comment by andyque** [comment]
因为我使用的是 company-ycmd 来补全 c++而不是 semantic，所以要删除 。
semantic 主要是用来 parse c/c++文件，然后可以调用 helm-semantic-or-imenu 方法，可以快速地跳转到定义和函数。
