### ISSUE TITLE
刚接触spacemacs，从github上下载下来的包文件经常错误

### ISSUE THREAD

**Issue by aialin** [zilongshanren/spacemacs-private#10]
看到你的一篇教程，提到可以采用你的配置，请问你这份配置应该如何使用才能兼容进spacemacs？

PS：我的工作系统是Windows 32bit，看官方文档推荐的是w64，不知是否会有冲突。

谢谢你的帮助~

**Comment by zilongshanren** [comment]
我的配置在mac上面本来就是兼容spacemacs的，我一直用的最新版本的spacemacs

至于windows，建议按照Spacemacs官方推荐的64位。

**Comment by aialin** [comment]
谢谢回复，可能我没表达清楚。
我有一份spacemacs配置，你的配置是直接拷贝覆盖到.emacs.d中就可以吗？
以前没接触过，所以啰嗦一点，
谢谢帮助~^_^

**Comment by zilongshanren** [comment]
@aialin 
建议先看我的视频，https://github.com/zilongshanren/Spacemacs-rocks/issues/4
