### ISSUE TITLE
emacs 菜单问题

### ISSUE THREAD

**Issue by programes** [zilongshanren/spacemacs-private#100]
使用emacs 编辑文件时 新出来的模式选项下面没有下拉菜单，是一片黑色的下拉条，file，edit，options，buffers，tools， help 等选项都有下拉菜单。比如我编辑的是C/CPP文件 出现的C++选项就是黑色下拉条，没有下拉菜单类似的gtags也是如此。

**Comment by programes** [comment]
补充说明：在terminal 下使用emacs命令打开文件就不会出现上诉问题。只有在emacs-gui格式下使用open file时才会出现如下问题。
使用的系统是ubuntu16.04.1 emacs 25.1 spacemacs 0.200

**Comment by zilongshanren** [comment]
我现在用的 mac，也没有办法帮你，你把这个问题发到 emacs-china.org 上面去吧。
