### ISSUE TITLE
YCMD 设置问题

### ISSUE THREAD

**Issue by JaydenZJX** [zilongshanren/spacemacs-private#101]
你好，
我现在下载好了ycmd －－clang 但是我应该怎么样把他们连在一起。就是说当我打开一个。cc file 他会自动加入 ycmd －－clang  补全

**Comment by zilongshanren** [comment]
这个一两句话也说不清楚啊，你需要下载一个 emacs-ycmd 的 package，然后根据 package 的 README 去配置就好了。

**Comment by JaydenZJX** [comment]
好的 谢谢了
