### ISSUE TITLE
Lua company报错

### ISSUE THREAD

**Issue by wolfand11** [zilongshanren/spacemacs-private#104]
Company: An error occurred in auto-begin
Symbol’s value as variable is void: company-frontends
Error running timer ‘company-idle-begin’: (void-variable company-frontends)

我查了一下lua-mode 目前还不支持 company
https://github.com/immerrr/lua-mode/issues/87

下面这个可以
https://github.com/ptrv/company-lua

**Comment by zilongshanren** [comment]
本来就要安装 company-lua 和 company-mode 呀
