### ISSUE TITLE
如何打开ｎｅｏｔｒｅｅ，ｓｐａｃｅｍａｃｓ默认快捷键失效

### ISSUE THREAD

**Issue by xushaobo** [zilongshanren/spacemacs-private#106]
ｎｅｏｔｒｅｅ插件是ｓｐａｃｅｍａｃｓ默认安装的插件，类似ｖｉｍ下的ｎｅｒｄｔｒｅｅ，查找文件目录很方便，但是这个配制下原本的＜ｓｐａｃｅ＞　ｆ　ｔ，快捷键失效了

**Comment by zilongshanren** [comment]
neotree 这个插件应该是被我 exclude 掉了，你可以加回来，因为我不使用 neotree，我喜欢直接用 dired

**Comment by xushaobo** [comment]
还有个问题，org agenda view
在我这里会同一件事件显示两遍，是我自己加了配置的原因吗，不知道可能是哪个函数导致的，现在看起来很吃力，我删除了自己的配置，直接用了您的配置还是有这个问题。

2016-10-21 14:46 GMT+08:00 子龙山人 notifications@github.com:

**Comment by zilongshanren** [comment]
@xushaobo  显示两遍是不是你加了 schedule 和 deadline 属性，能否载个图看看？

**Comment by xushaobo** [comment]
嗯嗯，已经解决了，agenda-file,有重复导致的问题，自己配置的原因

2016-10-26 7:22 GMT+08:00 子龙山人 notifications@github.com:
