### ISSUE TITLE
建議把dotfiles裏的配置刪掉

### ISSUE THREAD

**Issue by erstern** [zilongshanren/spacemacs-private#11]
我看了您的配置，對着這裏的
https://github.com/zilongshanren/dotfiles/blob/master/.spacemacs
這份配置調式了一段時間，當然也學了一些東西。
只是版本舊了，爲了避免歧義，建議還是只留一處吧。

**Comment by zilongshanren** [comment]
@erstern 
用develop分支呀。我保留master分支是因为以前Spacemacs是这样的

**Comment by zilongshanren** [comment]
@erstern 
既然有这个歧义，那我还是删除吧

**Comment by erstern** [comment]
我說的是這個地方：
https://github.com/zilongshanren/dotfiles
只有master啊，
我是後來才找到 spacemacs-private 這個項目裏來的。

**Comment by zilongshanren** [comment]
@erstern 
已删除
