### ISSUE TITLE
Ruby EnhRuby Mode 下缩进问题

### ISSUE THREAD

**Issue by ghost** [zilongshanren/spacemacs-private#110]
前天刚刚换过了师傅的配置，用了两天发现 Ruby 下面代码自动缩进在 `EnhRuby Mode` 下有问题。

![2016-10-30 18_07_19](https://cloud.githubusercontent.com/assets/3349406/19835870/052c3b7c-9ecc-11e6-8d7a-aff341004ebd.gif)

顺便问下 `[???]` 行首这个是什么东西？又的时候会变成函数的名字（不知道是什么时候就变了）？

**Comment by zilongshanren** [comment]
@li-xinyang  当光标在函数上面则会显示函数名，否则会显示？？

你在 end 后面再回车一下好像就正确的？

**Comment by zilongshanren** [comment]
@li-xinyang  你也可以在 end 后面再按一次 TAB 键就可以了，这个跟 python 是一样的

**Comment by ghost** [comment]
这样是可以解决问题，谢谢。不过函数名这个功能没什么反应，不知道什么时候就更新，有的时候就完全不变。师傅你为什么需要这个功能呢？是因为有的时候一个函数太长了一个屏幕显示不下吗？

**Comment by zilongshanren** [comment]
@li-xinyang  
是的，你也可以关闭这个功能， 把 `which-function-mode` 关闭即可

**Comment by zilongshanren** [comment]
@li-xinyang 

推荐换回 ruby-mode  

https://emacs-china.org/t/spacemacs-ruby-layer/1496/3

**Comment by ghost** [comment]
在发现问题后我就已经换回去了 :D
