### ISSUE TITLE
使用ivy切换buffer时历史buffer高亮如何去掉

### ISSUE THREAD

**Issue by panlei7** [zilongshanren/spacemacs-private#115]
当使用暗色主题时，SPC b b后出现关闭过的历史buffer颜色闪瞎眼了，请问如何把历史buffer去掉，或者把颜色改一下

**Comment by zilongshanren** [comment]
你设置 `ivy-use-virtual-buffers` 为 nil 就可以在 buffer 里面把历史去掉了，另外，通过customize-group ->   ivy-faces  -> Ivy Virtual 就可以了。
