### ISSUE TITLE
emacs CPU占用100%

### ISSUE THREAD

**Issue by SmartAI** [zilongshanren/spacemacs-private#116]
系统： OSX 10.12.1
Emacs 版本： 25.1
orgmode 版本：9.0
spacemacs版本：最新develop分支

经常出现在 `org agenda rebuild` 之后卡死，另外发现编辑org layer的配置非常卡

<img width="659" alt="1" src="https://cloud.githubusercontent.com/assets/19516876/20290733/d8397744-ab1c-11e6-9f6f-467f43b03b80.png">

**Comment by zilongshanren** [comment]
@minmatrix  请问你是否使用的是我的配置？
我这边好像从来没遇到过类似的错误，如何重现呢？

**Comment by zilongshanren** [comment]
@minmatrix  
当 cpu 100% 以后，可以在 terminal 里面输入 `pkill -SIGUSR2 -i emacs` 然后此时 Emac 会恢复正常，并且有一个 stacktrace， 你载个图看看，是什么导致你 CPU 100%的

**Comment by SmartAI** [comment]
@zilongshanren 对的，private用的你的配置，不过这个不是很好重现，等下次遇到了我再贴上来。不过我今天又遇到了python complete方面的问题我重新开一个issue

**Comment by SmartAILM** [comment]
||Key Create| Encrypt | Decrypt | Create Signature | Verify Signature|
|---|---------|---------|---------|------------------|-----------------|
|512|  0.0255830287933 |0.00904011726379| 0.0116419792175 |   0.00936889648438 |0.0108358860016|
|1024| 0.0359930992126 |0.00812792778015| 0.0129060745239 |   0.012745141983|   0.00996994972229|
|2048| 0.251528978348 | 0.00819993019104| 0.00938391685486 |  0.00844597816467| 0.012176990509|
|4096| 2.32796406746 |  0.00832200050354| 0.0105500221252| 0.0100429058075|  0.0080988407135|
