### ISSUE TITLE
emacs 启动错误

### ISSUE THREAD

**Issue by 2ming** [zilongshanren/spacemacs-private#119]
错误提示：An error occurred while setting layer variable chinese-enable-fcitx (error: (void-variable nReleaseil)). Be sure to quote the value if needed.

这是输入法问题么？

**Comment by zilongshanren** [comment]
@2ming  你是什么系统？ 建议去 fcitx 的仓库去提 issue。我现在没有用 fcitx 了。

**Comment by 2ming** [comment]
用的macOS ，我试试别的方法

**Comment by 2ming** [comment]
同事推荐Emacs，刚开始学习，非常感谢大神出的教程，拜谢！！！

**Comment by zilongshanren** [comment]
@2ming  不客气。 有问题可以去 emacs-china.org 发帖。
