### ISSUE TITLE
請教 ace-pinyin 的用法

### ISSUE THREAD

**Issue by erstern** [zilongshanren/spacemacs-private#12]
我最近也改到 spacemacs 的 develop 分支了，但是發現 ace-pinyin 不聽使喚了。
以前的配置是這麼寫的：
```
 (define-key evil-normal-state-map (kbd ", SPC") 'ace-jump-char-mode)
```
（我本想綁定到 SPC SPC，但是沒成功。）

現在依然是 chinese layer 的參數，包含 chinese-enable-avy-pinyin t ，user-config 裏面的還按照以前的失效了，改成 avy-goto-char 等等都無效。
在您的這份 spacemacs-private 裏我沒找到有關 ace/avy 的配置和 key-binding，請教把 ace-pinyin 單獨拿出來用，該如何執行？

**Comment by zilongshanren** [comment]
你需要通过最新的spacemacs 的develop分支。默认ace-pinyin已经支持avy了

**Comment by erstern** [comment]
Thx！
我綁定了 'evil-avy-goto-char 就可以用了。

**Comment by zilongshanren** [comment]
@erstern OK.
