### ISSUE TITLE
安装完出现这个警告怎么办？

### ISSUE THREAD

**Issue by canxer314** [zilongshanren/spacemacs-private#122]
Auto-evilication could not remap these functions in map ‘dired-mode-map’:
   - ‘dired-do-chgrp’ originally mapped on ‘G’
(Spacemacs) Warning: tern binary not found!

**Comment by zilongshanren** [comment]
@canxer314 
第一个警告：可以忽略。我记得 spacemacs 的 develop 分支好像没有这个 警告了。
第二个警告：你需要安装 `tern`，可以使用 `npm install -g tern`来安装。

**Comment by canxer314** [comment]
请问这个tern是vim-tern吗？直接pacman -S没有对应的包名

**Comment by zilongshanren** [comment]
@canxer314 
不是 vim-tern，就是一个 npm 工具而已，vim-tern 也是对这个工具的封装。

**Comment by canxer314** [comment]
请问emacs支持像atom那样细致的自定义代码风格配置吗？安装https://www.emacswiki.org/emacs/IndentingC#toc13上的内容配置了https://github.com/google/styleguide/blob/gh-pages/google-c-style.el好像也只管缩进风格而已，我想精确到每个变量跟运算符之间间隔一个空格那种，粗粗看完了您的文字版21天教程，没发现相关内容

**Comment by zilongshanren** [comment]
@canxer314 
建议你把问题描述清楚，然后去 emacs-china.org 上面开帖和大家一起讨论。
我目前不是很清楚你说的 atom 那种”细致“的代码风格是什么。

**Comment by canxer314** [comment]
好的
