### ISSUE TITLE
ycmd的问题

### ISSUE THREAD

**Issue by benbenji** [zilongshanren/spacemacs-private#123]
山人你好 我直接用了你的配置 可是我安装完了ycmd之后 发现他好像没有生效 请问还需要什么其他的配置吗？

**Comment by zilongshanren** [comment]
@benbenji 
我目前的配置里面已经没有 ycmd 了。

**Comment by benbenji** [comment]
那你现在用什么新的方法进行代码补全和跳转吗？

**Comment by zilongshanren** [comment]
@benbenji  我现在只用 tags 来补全了。

**Comment by benbenji** [comment]
好的 谢了 祝好！
