### ISSUE TITLE
关于缩进问题

### ISSUE THREAD

**Issue by que01** [zilongshanren/spacemacs-private#130]
我修改了layers/zilongshanren-ui/packages.el
```
-    (setq-default tab-width 4)
+    (setq tab-width 2 indent-tabs-mode nil)
```
但是现在还是有点问题 当在vim的normal模式下按o新加一行，或者s-enter新加一行都会出现一点问题
按o时候：
<img width="320" alt="12345" src="https://cloud.githubusercontent.com/assets/5241691/21375151/9b32ed92-c766-11e6-9838-44476ad86cd2.png">
这时光标缩进了4个不是预期的2个

按s-enter后:
<img width="384" alt="123" src="https://cloud.githubusercontent.com/assets/5241691/21375188/de7b380c-c766-11e6-80c4-ad5c7102e57b.png">
此时缩进也是4个 还把光标所在行也给缩进了2个

操作前：
<img width="343" alt="1234" src="https://cloud.githubusercontent.com/assets/5241691/21375208/fb2e4e08-c766-11e6-9497-8bf09825f89f.png">
当我操作时候光标都在这个图中所示。

实在不知道如何处理，vim转emacs就别这个难住了。希望得到帮助，谢谢

**Comment by zilongshanren** [comment]
@que01 
编辑 js 的时候，你需要设置 js-indent-level 这个变量来调整 indent 的数量。

**Comment by que01** [comment]
@zilongshanren  不好意思，之前很想直接关掉这个issue的。不知道有出于什么原因没关。js-indent-level 这个我加上了在js文件里面确实可以解决问题，不过我自己安装了vue-mode之后，他就还是4个空格,😰。所以回来求助一下，虽然有点伸手党的感觉，但是我真的试过很多次，实在解决不了。——能不能给配置加上vue支持呢?😬

**Comment by que01** [comment]
自己创建了一个layer 问题解决了。抱歉添麻烦了😬
