### ISSUE TITLE
package eldoc not initialized in layer typescript

### ISSUE THREAD

**Issue by sangjeedondrub** [zilongshanren/spacemacs-private#134]
这个什么原因：
Warnings:
-package eldoc not initialized in layer typescript, you may consider removing
this package from the package list or use the :toggle keyword instead of a
`when' form.      
- tern binary not found!   

对于后一个问题，通过`brew install homebrew/emacs/tern`安装tern之后也无法解决

**Comment by zilongshanren** [comment]
@sangjeedondrub 
第一个警告更新 spacemacs 的 develop 分支到最新分支，同时更新我的配置到最新分支。

第二个问题，使用 node install -g tern 即可安装。

**Comment by sangjeedondrub** [comment]
已根据你的指导完成配置修复，谢谢。
