### ISSUE TITLE
edit-ends-of-lines函数绑定快捷键错乱

### ISSUE THREAD

**Issue by y2kbug** [zilongshanren/spacemacs-private#142]
emacs-version is "25.2.1"
spacemacs-version is 0.200.7

查看zilongshanren-misc/packages.el中配置`edit-ends-of-lines函数绑定的快捷键是`(define-key endless/mc-map "\C-e" #'mc/edit-ends-of-lines)`测试发现`Control-e`不生效，同时使用'SPC h d f'查看`edit-ends-of-lines`绑定的快捷见是"It is bound to C-x m C-e."

**Comment by zilongshanren** [comment]
已经在论坛回复。
