### ISSUE TITLE
启动错误 error: (void-function spacemacs|add-company-backends))

### ISSUE THREAD

**Issue by DL-85** [zilongshanren/spacemacs-private#143]
An error occurred while post-configuring company in layer zilongshanren-programming (error: (void-function spacemacs|add-company-backends))
系统：ubuntu 14.04
emacs 版本：25.1.1
spacem 版本：0.200.8

启动spacemacs时即出现这样的错误

**Comment by iiwmind** [comment]
怎么解决的呢？？ 我系统用的win7，  emacs25.2.1
