### ISSUE TITLE
你好，子龙山人，怎么配置 vue-mode 呢

### ISSUE THREAD

**Issue by huangyingwen** [zilongshanren/spacemacs-private#145]
我照着官方文档配置不成功，https://github.com/CodeFalling/vue-mode
`(defun zilongshanren-programming/init-vue-mode ()
  (use-package vue-mode))
`
这一段我添加到 zilongshanren-programming/packages.el
vue-mode 加到这里了 zilongshanren-programming-packages 
出来的模式和文档上不一样

![image](https://cloud.githubusercontent.com/assets/1214875/25232368/a0456304-260d-11e7-8c49-d6a059af7900.png)

**Comment by zilongshanren** [comment]
这个最好去作者的 github 上面提 issue 吧，我本人不用 vue-mode
