### ISSUE TITLE
 如何改变org-mode标题中文字体？

### ISSUE THREAD

**Issue by ryandroll** [zilongshanren/spacemacs-private#146]
如图，标题与内文的中文字体不一致，但是在设定档看不出来标题所引用的字体。

要如何做到改变标题字体让他与内文的字体一致。

<img width="1274" alt="2017-04-23 6 07 26" src="https://cloud.githubusercontent.com/assets/19866320/25312594/1acdea8a-2850-11e7-99a8-5a0159c1bf16.png">

**Comment by Einlain** [comment]
M-x 运行 describe-face 可以定制emacs大部分的界面元素

**Comment by ryandroll** [comment]
谢谢!!!
