### ISSUE TITLE
evilify error

### ISSUE THREAD

**Issue by tsimaa** [zilongshanren/spacemacs-private#15]
今天搞备份，不小心把 .emacs.d .spacemacs.d 都清空了，所有设置都丢了，没办法重新再来。
（好在 spacemacs 也是前几天才装的）

装载你的spacemacs-private时出现 Symbol's function definition is void: evilify，

昨天安装你的配置时还没有这样的错误，今天不知怎么就有了，请问这是什么问题导致的呢？？

谢谢。

**Comment by zilongshanren** [comment]
@tsimaa 
再更新一下我的配置，因为spacemacs更新了。

**Comment by Qxavier** [comment]
刚使用了最新的spacemaces dev分支和你的配置，启动时仍会出现这个问题

**Comment by zilongshanren** [comment]
@tsimaa  @Qxavier  
再同步一下我的最新分支，我刚刚修复了。
