### ISSUE TITLE
启动 emacs 报错 

### ISSUE THREAD

**Issue by shangzongyu** [zilongshanren/spacemacs-private#150]
启动的时候报错如下：
![93489e9c-c95a-4391-8222-fd1e25e2e5dc](https://cloud.githubusercontent.com/assets/3054443/26721859/22cf6d3c-47c0-11e7-91a1-c4810cbdd310.png)

**Comment by zilongshanren** [comment]
我的没问题啊，你是不是使用的 spacemacs的最新 develop 分支啊，master 分支我是没有 check 的。

**Comment by chenkaiC4** [comment]
@TomShine  spacemacs 的代码要使用dev分支的
