### ISSUE TITLE
 why editing style did not work here?

### ISSUE THREAD

**Issue by Dakemao** [zilongshanren/spacemacs-private#151]
When i clone your configure on my ubuntu os. 
emacs version is  25.1
i changed init.el like blow:
dotspacemacs-editing-style 'emacs

but it's did not work . It's also in vim style.
what should i do?
                                 THX.

**Comment by zilongshanren** [comment]
I don't use `emacs` editing style, so I have no idea what to do.

I suggest you try the original spacemacs version.
