### ISSUE TITLE
每次启动都提示installing package,而且时间特久

### ISSUE THREAD

**Issue by francioshu** [zilongshanren/spacemacs-private#152]
每次启动都提示installing package,而且时间特久
--> installing package: highlight-global@zilongshanren-misc... [3/3]

**Comment by Dakemao** [comment]
用的什么源？

**Comment by zilongshanren** [comment]
@francioshu  检查一下你的配置源，最好使用 emacs-china 的，另外，建议不要使用最新的 spacemacs develop 分支，目前这几天的版本有点问题。

**Comment by NicodeLee** [comment]
确实有这个问题，跟着视频配置下来。不过也正式入spacemacs了。
