### ISSUE TITLE
配置没有生效

### ISSUE THREAD

**Issue by elementsix** [zilongshanren/spacemacs-private#153]
![2017-06-17 11 27 19](https://user-images.githubusercontent.com/29254350/27249801-3972a9b4-5350-11e7-8f81-5a060a407a52.png)
配置了你的文件，没有生效，不知问题在那，初学者菜鸟，盼复

**Comment by chenkaiC4** [comment]
1. 要下载 spacemacs 的 dev 分支代码，以及这个项目的 dev 代码。都是dev分支。

```
#clone spacemacs repo and use develop branch
git clone https://github.com/syl20bnr/spacemacs.git ~/.emacs.d -b develop

#clone zilongshanren layer and checkout develop branch
git clone https://github.com/zilongshanren/spacemacs-private.git ~/.spacemacs.d/
```


2. 删除（如果有的话）或者备份本地主目录的 `.spacemacs` 文件(比如重命名为 .spacemacs.bak )，否则这个项目的配置不会被 spacemacs 配置使用
