### ISSUE TITLE
启动时出现问题，add-company-backends

### ISSUE THREAD

**Issue by chenkaiC4** [zilongshanren/spacemacs-private#154]
![image](https://user-images.githubusercontent.com/7543145/27583173-1d52efdc-5b66-11e7-9213-66877a9ca062.png)

系统信息
![image](https://user-images.githubusercontent.com/7543145/27583225-42644334-5b66-11e7-925d-f58bdd6e9153.png)

似乎是大侠你的个人公司环境配置，这个因人而异，是该如何处理？

**Comment by aGolduck** [comment]
用 develop 分支的 spacemacs

**Comment by chenkaiC4** [comment]
@wpchou 谢谢，现在我已经使用spacemacs的 dev分支了，但是安装时，依然报错

![image](https://user-images.githubusercontent.com/7543145/27613318-797a9370-5bcd-11e7-8595-e4de1e756cfe.png)

我到相应的地址去查了，的确没有该文件。似乎是包源的更新出了点问题。我切换为默认的源，依然是缺少这两个包。

` evil-org (error: (file-error https://elpa.gnu.org/packages/org-plus-contrib-20170622.tar Not found))`

`org-brain (error: (file-error https://elpa.gnu.org/packages/org-plus-contrib-20170622.tar Not found))`

现在emacs卡成这个样子，119/359，走不下去了
![image](https://user-images.githubusercontent.com/7543145/27613712-b1b5f1ec-5bcf-11e7-8096-6b8a113367bf.png)

**Comment by aGolduck** [comment]
先翻墙，或者先把源换成 emacs–china 的源，自己搜一下

**Comment by zilongshanren** [comment]
@chenkaiC4 使用 emacs-china 的源就没问题  https://elpa.emacs-china.org/

另外，检查一下你的代理。
