### ISSUE TITLE
按你的配置，ycmd默认打不开，是不是Programming layer没有生效？

### ISSUE THREAD

**Issue by anthony-zg** [zilongshanren/spacemacs-private#155]
已经在init.el/dotspacemacs-configuration-layers内增加了     
zilongshanren
zilongshanren-programming
这两项了。
手动在init.el增加ycmd及相关配置是可以的。但是我全局搜索看到programming里有配置，只是启动不了这个Layer，求解

**Comment by zilongshanren** [comment]
@anthony-zg 
我最新的配置已经放弃使用 ycmd 了，所以，现在可能是跑不起来了

**Comment by anthony-zg** [comment]
明白，你现在ycmd的替代插件是什么？
另外：zilongshanren-programming的加载方式是什么？现在是只有zilognshanren这一个layer生效吗？我ag只看到declare-layers，没找到加载的代码,手动在Init.el中添加了这个layer看上去也不生效。（刚从vim转到emacs）
