### ISSUE TITLE
通过代理无法下载emacs插件，想在公司使用spacemacs可以怎么办呢

### ISSUE THREAD

**Issue by pzh2386034** [zilongshanren/spacemacs-private#157]
## 不知道大家对于这种情况有没有好的解决方法？谢谢大家了~~

**Comment by aGolduck** [comment]
https://elpa.emacs-china.org/

**Comment by pzh2386034** [comment]
公司使用的是有密码的代理，不代理不管国内外的网络都无法使用；目前查的方法来看，始终无法解决该问题。
最后通过打包.emacs.d及.spacemacs.d目录解决

**Comment by aGolduck** [comment]
https://github.com/redguardtoo/elpa-mirror
