### ISSUE TITLE
ivy补全目录是什么？

### ISSUE THREAD

**Issue by panlei7** [zilongshanren/spacemacs-private#159]
原始的配置文件下，SPC f f之后，输入几个字母，找到备选项，输入/就可以补全目录，很方便。现在在这个配置文件下，输入/就直接打一个/并没有补全，是不是在哪里设置过了？

**Comment by devbins** [comment]
我这里碰到的情况是使用 SPC f f 输入文件名前几个字母，按 TAB 不能自动补全路径，提示 ls does not support --dired; see 'dired-use-ls-dired' for more details.
我把 zilongshanren-misc/packages.el 中 (define-key ivy-minibuffer-map (kbd "TAB") 'ivy-call)注释了就可以了。找了我一个晚上加一个早上,终于解决了。

**Comment by zilongshanren** [comment]
@binsheng 感谢指出，最新的配置我把这个注释掉了。
