### ISSUE TITLE
关于一些字体

### ISSUE THREAD

**Issue by tsimaa** [zilongshanren/spacemacs-private#16]
guanghui/packages.el里语句：
 setq org-bullets-bullet-list 
 org-pomodoro-short-break-finished-hook
用到的一些符号"🐉" "🐠" "🐬" "🐤" "🐝" "💪"来自于什么字体文件？
![snap1](https://cloud.githubusercontent.com/assets/1050513/11316030/cdcbf166-9037-11e5-91de-34d44cd765bc.png)
变成这样了。

**Comment by zilongshanren** [comment]
@tsimaa 
Mac系统自带的。
