### ISSUE TITLE
所有的包都无法下载

### ISSUE THREAD

**Issue by colmugx** [zilongshanren/spacemacs-private#161]
山哥好，我下载了您的配置，然后会弹出三次emacs-china继续连接询问。之后就一直弹出说，找不到包，是否包名正确（我就简单翻译了下，因为配置被我删了……）。结果100来个都没成功安装。

另外我自己有一个配置，不过最后还是懒得折腾，想直接用您的。我配置spacemacs想做前端开发

**Comment by zilongshanren** [comment]
建议看看你的网络是否有问题，是否有代理

**Comment by colmugx** [comment]
有开代理，默认翻的。
网络没问题，我重新更新我的配置和重新下spacemacs都没问题的
