### ISSUE TITLE
启动卡住

### ISSUE THREAD

**Issue by chenzhaobo** [zilongshanren/spacemacs-private#164]
在启动emacs的时候，下面三个包没有安装，我在网络环境在安装下面三个包要卡很久等待失败后才能启动emacs：
graphviz-dot-mode、highlight-global、blog-admin
请问能有什么方法规避这个问题吗？

**Comment by chenzhaobo** [comment]
就是在refresh package之后installing package，卡非常的久。其他的包安装完成了，就这三个包每次启动都得来一次安装。

**Comment by zilongshanren** [comment]
@cppddz 看看网络代理是不是有问题，另外可以试着更新我的最新配置试试。
