### ISSUE TITLE
ivy重复init了

### ISSUE THREAD

**Issue by ztlevi** [zilongshanren/spacemacs-private#165]
你好。
你在dotspacemacs-configuration-layers里面已经加入了ivy，然后在defun zilongshanren-misc/post-init-swiper ()中又重新加载ivy了。。

然后大多数功能和key spacemacs已经完善了。目前看下来需要添加的只有一个ivy call。

谢谢！

**Comment by zilongshanren** [comment]
这个最新版本应该没问题了。
