### ISSUE TITLE
考虑我单独维护一份Chinese layer

### ISSUE THREAD

**Issue by zilongshanren** [zilongshanren/spacemacs-private#17]
因为我给Spacemacs官方提PR的处理速度比较慢，我想自己维护一个chinese layer，不过由于layer名字不能重复，大家觉得 `chinese-extra`这个名字怎么样，专门用来存放Spacemacs还没有收录的特性。
而且这个`chinese-extra` layer也可以添加更多的与中文相关的功能。

**Comment by zilongshanren** [comment]
比如 https://github.com/syl20bnr/spacemacs/pull/3847  这个添加fcitx的PR就迟迟没有合并。

**Comment by geekplux** [comment]
chinese-extra 可以啊

**Comment by zilongshanren** [comment]
@geekplux 
哈哈，要不要整呀。。。 还是等下吧。

**Comment by Carter-Pro** [comment]
支持！

**Comment by 0000-bigtree** [comment]
整！

**Comment by xiaoDC** [comment]
@zilongshanren 请问spacemacs vim 模式下如何能使用 https://github.com/kshenoy/vim-signature 这种插件

**Comment by zilongshanren** [comment]
由于我已经很少写 chinese 了，这个 layer 的想法暂时作罢
