### ISSUE TITLE
(error: (wrong-number-of-arguments if 1))

### ISSUE THREAD

**Issue by GinShio** [zilongshanren/spacemacs-private#177]
您好，子龙山人，在clone了Spacemacs与您的配置之后，运行spacemacs发生了错误，错误提示如标题：(error: (wrong-number-of-arguments if 1))
详细请看：https://emacs-china.org/t/topic/6170/3

**Comment by elementsix** [comment]
遇到同样的问题

**Comment by elementsix** [comment]
始终安装不好，希望大神可以fix下这个issues

**Comment by zilongshanren** [comment]
@elementsix @GinShio  已经fix了，更新最新的就行。

最新的代码，我把tern和company-tern去掉了，同时禁用了行号，关注一下。

**Comment by elementsix** [comment]
@zilongshanren ，谢谢，已经更新到最新的了，

**Comment by GinShio** [comment]
@zilongshanren 请问禁用了行号要如何开启

**Comment by zilongshanren** [comment]
@GinShio 
把 init.el 里面的 user-config函数的 

```
  (global-display-line-numbers-mode -1)
```

改成

```
  (global-display-line-numbers-mode 1)
```
