### ISSUE TITLE
c-h v出来的参数只有8000多，在我没用子龙的配置前比这个多很多，这个是哪边设置有问题么

### ISSUE THREAD

**Issue by futianfeixu** [zilongshanren/spacemacs-private#179]

**Comment by zilongshanren** [comment]
这个不太清楚。。。看看有没有缺少什么变量吧

**Comment by futianfeixu** [comment]
似乎是因为预加载的问题，比如org-agenda，我如果还没调用这个，是找不到这个的帮助文档的

**Comment by futianfeixu** [comment]
> 这个不太清楚。。。看看有没有缺少什么变量吧

似乎是因为预加载的问题，比如org-agenda，我如果还没调用这个，是找不到这个的帮助文档的，这个需要做什么配置么？
