### ISSUE TITLE
配置报错，以下错误是不是导致org字体有点小得原因？

### ISSUE THREAD

**Issue by forzajuve** [zilongshanren/spacemacs-private#18]
An error occurred while post-configuring org in layer zilongshanren (error: (invalid-function org-babel-header-args-safe-fn))
Error in dotspacemacs/user-config: Font not available: #<font-spec nil nil Source\ Code\ Pro nil nil nil nil nil 14 nil nil nil ((:name . "Source Code Pro:pixelsize=14") (user-spec . "Source Code Pro:pixelsize=14"))>

**Comment by zilongshanren** [comment]
不是，这是一个org的bug，你需要手动找到ob-R.el，然后byte-compile-file这个文件，再重新启动Emacs就可以了。

**Comment by zilongshanren** [comment]
@forzajuve 
使用 `SPC h L` 就可以定位到ob-R.el文件

**Comment by forzajuve** [comment]
An error occurred while installing clj-refactor (error: (error Local variables entry is missing the suffix))

Error in dotspacemacs/user-config: Font not available: #<font-spec nil nil Source\ Code\ Pro nil nil nil nil nil 14 nil nil nil ((:name . "Source Code Pro:pixelsize=14") (user-spec . "Source Code Pro:pixelsize=14"))>,按你说的做了，但还有这个错误

**Comment by zilongshanren** [comment]
@forzajuve  你需要安装Source Code Pro字体 可以解决 `Error in dotspacemacs/user-config: Font not available: #,按你说的做了，但还有这个错误`。

如果你不用clj-refactor， 你可以把clj-refactor添加到`dotspacemacs-excluded-packages`中去。

这是一个已知bug，我给spacemacs作者提了，不过目前没人管。。。

不过也可能是我的配置问题。

**Comment by forzajuve** [comment]
好的，解决了，多谢
