### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by tomtsang** [zilongshanren/spacemacs-private#180]
- os: mac os 10.13.3
- emacs: 26.1
- spacemacs： 0.200.13@26.1, master分支

启动报错如下：
```
An error occurred while post-configuring company in layer zilongshanren-programming (error: (void-function spacemacs|add-company-backends))
Error in dotspacemacs/user-config: Symbol’s function definition is void: spacemacs|add-company-backends
```

事后，发现devlop分支，不会报这个错误，但是，还是希望把 在master分支上出现的这个问题，解决吧。

**Comment by zilongshanren** [comment]
master作者都不更新了，尽量使用 develop分支吧。

**Comment by iT-Boyer** [comment]
emacs 26.2 
termux andorid

Spacemacs master
spacemacs-private develop

出现同样的问题
