### ISSUE TITLE
有package无法安装，提示unavailable

### ISSUE THREAD

**Issue by LiErhua** [zilongshanren/spacemacs-private#181]
Found 3 new package(s) to install...
--> refreshing package archive: gnu... [3/3]
--> installing package: help-fns+@spacemacs-base... [1/3]
Package help-fns+ is unavailable. Is the package name misspelled?
--> installing package: hide-comnt@spacemacs-editing-visual... [2/3]
Package hide-comnt is unavailable. Is the package name misspelled?
--> installing package: info+@spacemacs-navigation... [3/3]
Package info+ is unavailable. Is the package name misspelled?

**Comment by zilongshanren** [comment]
看看是不是你的spacemacs没有使用develop分支？

**Comment by LiErhua** [comment]
spacemacs 和您的配置都是用的develop版本
```
➜  ~ cd .spacemacs.d
➜  .spacemacs.d git:(develop) ✗ ls
README.org    README_CN.org custom.el     ditaa.jar     init.el       layers        plantuml.jar  snippets
➜  .spacemacs.d git:(develop) ✗ cd ../.emacs.d
➜  .emacs.d git:(develop) ls
CHANGELOG.develop   COMMUNITY.org       Dockerfile.emacs25  README.md           core                elpa                layers              private             tests
CHANGELOG.org       CONTRIBUTING.org    Dockerfile.snapshot assets              doc                 init.el             news                spacemacs.mk
➜  .emacs.d git:(develop)
```

**Comment by zilongshanren** [comment]
@LiErhua 检查一下你的代理是否有问题，有些网络是需要配置 http_proxy代理的。
