### ISSUE TITLE
安装出错

### ISSUE THREAD

**Issue by weinix** [zilongshanren/spacemacs-private#184]
Errors: 
- An error occurred while installing blog-admin (error: (wrong-type-argument package-desc nil))

Setup:
- MacOS
- emacs 26.1
- I had to change below to get package install working, probably because I am in U.S

<img width="264" alt="image" src="https://user-images.githubusercontent.com/8346873/48447046-8cce3100-e760-11e8-9955-e66e1250b085.png">

最后，非常感谢您的工作，我从中了解到emacs说强大！希望能一直跟随您的脚步学习下去！

**Comment by weinix** [comment]
Restart emacs again got slightly different error:
Found 1 new package(s) to install...
--> refreshing package archive: gnu... [3/3]
--> installing package: blog-admin@zilongshanren-org... [1/1]

Errors:
error occurred while installing blog-admin (error: (wrong-type-argument package-desc nil))

**Comment by zilongshanren** [comment]
blog-admin has been removed, now this issue would disappear
