### ISSUE TITLE
请问 spacemacs 的 buffer 顶部的黄色 bar 作用是什么？用哪个 package 实现的？怎么去掉？

### ISSUE THREAD

**Issue by sherrywong1220** [zilongshanren/spacemacs-private#186]
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/19210342/50761432-5666eb00-12a5-11e9-80bd-feeddcce78e2.png">

**Comment by zilongshanren** [comment]
好像是显示的 which func mode, 试试搜索

```
(setq-default header-line-format
              '((which-func-mode ("" which-func-format " "))))
```

把这一行去掉。
