### ISSUE TITLE
Spacemacs） Error in dotspacemacs/usr-config

### ISSUE THREAD

**Issue by programes** [zilongshanren/spacemacs-private#188]
（Spacemacs） Error in dotspacemacs/usr-config: Symbol's function definition is void: spacemacs|add-company-backends
emacs 26.1 win64
system os :windows build 1809 update 201902
spacemacs :200.13[](url)

**Comment by programes** [comment]
![20190224090338](https://user-images.githubusercontent.com/6359325/53293677-2f438900-3813-11e9-8f2d-021f729ea0ad.png)

**Comment by programes** [comment]
So, what should I do ? Thanks.

**Comment by zilongshanren** [comment]
@programes  
Do you use the develop branch of spacemacs?

**Comment by programes** [comment]
NO,

**Comment by zilongshanren** [comment]
@programes 更新最新版本试试，应该已经解决了
