### ISSUE TITLE
如何禁用pangu-spacing?

### ISSUE THREAD

**Issue by WindWang2** [zilongshanren/spacemacs-private#19]
您好，我是emacs初学者，部分使用了您的配置。不喜欢pangu-spacing，不知道如何禁用。

**Comment by zilongshanren** [comment]
@WindWang2 
在你的.spacemacs.d/init.el文件里面找到 `dotspacemacs-excluded-packages':

`   dotspacemacs-excluded-packages '(magit-gh-pulls
                                    magit-gitflow
                                    evil-mc
                                    emmet-mode
                                    chinese-wbim
                                    chinese-pyim
                                    yasnippet
                                    srefactor
                                    org-download
                                    org-timer
                                    org-tree-slide
                                    ;; disable it for lispy-mode
                                    ;;https://github.com/abo-abo/lispy/issues/137
                                    evil-escape
                                    ;;At first, I should disable hydra in zilongshanren layer and install clj-refactor, after it is installed.
                                    ;; I could re-enable it again in zilongshanren layer.
                                    ;; clj-refactor
                                    ;;remove from spacemacs distribution
                                    ;; neotree
                                    leuven-theme
                                    gh-md
                                    evil-lisp-state
                                    spray
                                    evil-tutor
                                    define-word
                                    doc-view
                                    lorem-ipsum
                                    solarized-theme
                                    ;; remove mode for python layer
                                    nose
                                    pony-mode
                                    hy-mode)

`
下面是我自己禁用的一些package.

**Comment by WindWang2** [comment]
Thank you, 期待你的Spacemacs Rocks第二季！

**Comment by MilooHub** [comment]
@zilongshanren 

> 在你的.spacemacs.d/init.el文件里面找到 `dotspacemacs-excluded-packages':

现在这个是不是改成了 ~/.spacemacs 里的    **dotspacemacs-excluded-packages '()**

然后把不想使用的package名称（如 pangu-spacing）写到括号里即可？
