### ISSUE TITLE
安装配置出错，packages are unavailable

### ISSUE THREAD

**Issue by ZhengWG** [zilongshanren/spacemacs-private#190]
安装过程如下：
```
git clone https://github.com/zilongshanren/spacemacs .emacs.d
```
也试了（`git clone https://github.com/syl20bnr/spacemacs.git ~/.emacs.d -b develop`）
```
git clone https://github.com/zilongshanren/spacemacs-private.git ~/.spacemacs.d/
```
打开emacs后，所有的packages都没法安装，报错：
```
Package xxx is unavailable. Is the package name misspelled?
```
配置环境：
```
Ubuntu16.04
Emacs25.3
```

**Comment by QiKatherine** [comment]
我也重复试过很十多次，也出现这个问题，连安装主题都失败了。没办法只能使用原始的spacemacs配置，改几个layer凑合用。后来有次不死心，手动清空了.spacemacs.d文件，只clone子龙的spacemacs-private repo内容到本地.spacemacs.d文件。然后打开Emacs就成功了，（只有两个package（highlight-global和grahviz）稍微有点问题）。

Windows 10
Emacs 25.3

Update: 在Ubuntu Emacs 25.2.2也遇到了一样的问题。安装原spacemacs后，立刻用子龙的private repo里全部文件，替换掉.spacemacs.d里面的init.el，也顺利解决。

**Comment by ZhengWG** [comment]
> 我也重复试过很十多次，也出现这个问题，连安装主题都失败了。没办法只能使用原始的spacemacs配置，改几个layer凑合用。后来有次不死心，手动清空了.spacemacs.d文件，只clone子龙的spacemacs-private repo内容到本地.spacemacs.d文件。然后打开Emacs就成功了，（只有两个package（highlight-global和grahviz）稍微有点问题）。
> 
> Windows 10
> Emacs 25.3
> 
> Update: 在Ubuntu Emacs 25.2.2也遇到了一样的问题。安装原spacemacs后，立刻用子龙的private repo里全部文件，替换掉.spacemacs.d里面的init.el，也顺利解决。

请问你装的上spacemacs是stable版本还是develop版本呢？是这个吗:
`git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d`

**Comment by ZhengWG** [comment]
发现还是网络延迟的问题，将 `inti.el`中的`dotspacemacs-elpa-timeout 5`改成`dotspacemacs-elpa-timeout 300`即可

**Comment by QiKatherine** [comment]
试了一下成功了，层主威武，感谢。
