### ISSUE TITLE
pyim 未报错但也不能用

### ISSUE THREAD

**Issue by lyserenity** [zilongshanren/spacemacs-private#195]
我几乎照抄了 layers/zilongshanren-misc/packages.el 里 pyim 的配置，也按照 [在Mac版的Emacs中使用RIME输入法](https://manateelazycat.github.io/emacs/2019/07/24/use-rime-in-emacs.html) 编译了。查看 *Messages* 和执行了 ``(liberime-get-schema-list)`` 也有正确显示，但 ``toggle-input-method``打字还是英文，而且 modeline 显示如图：
![image](https://user-images.githubusercontent.com/32646062/62003133-c7d49100-b144-11e9-85bb-360b9621403b.png)

想请问还有什么方法可以查看看到底是哪里出了问题？

**Comment by zilongshanren** [comment]
你先看看，RIME输入法在其他app中可以使用不。然后再看看schema 是否选择正确

**Comment by lyserenity** [comment]
RIME 输入法可以用，schema 也应该是对的（是执行 ``(liberime-select-schema "luna_pinyin")``这个吗？）

**Comment by zilongshanren** [comment]
你如果照抄了我的配置，那么在prog-mode中，只有在注释和字符串中才可以输入中文。输入完英文后，空格后可以再输入中文。建议去掉Probe相关的函数再试试。

另外，你可以试试，不使用rime的pyim是否正常工作。

**Comment by lyserenity** [comment]
我刚试了一下，不用 rime 的 pyim 可以用。但 rime 还是不行，可能依旧是哪里有问题，先暂时放弃好了。😢

**Comment by zilongshanren** [comment]
恩，建议看看 ` (liberime-start "/Library/Input Methods/Squirrel.app/Contents/SharedSupport" (file-truename "~/Library/Rime"))` 的执行结果是否正确

**Comment by lyserenity** [comment]
我后来无聊就把 ``post-init-pyim``里的代码轮番执行了一遍，结果发现如果打开 emacs 后，重新执行一次 ``progn``那个()里的整块区块，pyim 就能用了。因为我实在对 emacs 不了解，想请问有没有什么思路可以帮助我排查一下是哪里出了问题？

**Comment by lyserenity** [comment]
我找到了，大概是 ``(set-language-environment "UTF-8")`` 这造成的，反正去掉就正常了。
(相关讨论串：https://github.com/tumashu/pyim/issues/82)
