### ISSUE TITLE
org-mode 中文、西文之间自动显示空格的问题

### ISSUE THREAD

**Issue by erstern** [zilongshanren/spacemacs-private#20]
西文现在只包含了常见的字母，我添加某些数学公式时候发现不支持希腊字母，还有 `@` 、 `%` 这些符号和 `ß` `ü` 这些非英语的字母也都是不支持的。
能否扩大支持的范围？

**Comment by erstern** [comment]
抱歉，我不知道这个问题是不是属于 Chinese layer ，只是提个建议。

**Comment by zilongshanren** [comment]
@erstern 可以给pangu-space这个package的作者提issue https://github.com/coldnew/pangu-spacing
