### ISSUE TITLE
spacemacs打开不了文件了

### ISSUE THREAD

**Issue by forzajuve** [zilongshanren/spacemacs-private#21]
spacemacs打开不了文件了，今早.emacs.d   和.spacemacs.d    下git pull之后再打开spacemacs之后，想打开任何文件都打来不了。
searching for program:no such file or directory,fctix-remote

**Comment by zilongshanren** [comment]
@forzajuve  把chinese layer里面的enable-fctix  设置为nil吧

**Comment by forzajuve** [comment]
(defvar chinese-enable-avy-pinyin t
  "Enable ace-pinyin in avy-goto-char")

(defvar chinese-enable-fcitx nil
  "Enable fcitx to help writing Chinese in Evil mode.")
是chinese下的config.el吗，本来就是nil啊

**Comment by forzajuve** [comment]
(chinese :variables chinese-default-input-method 'wubi
              chinese-enable-youdao-dict t
              chinese-enable-fcitx nil)
原来实在spacemacs.d/init.el里面设置
