### ISSUE TITLE
自动纠正;的位置

### ISSUE THREAD

**Issue by danielwuz** [zilongshanren/spacemacs-private#22]
你好，我在youtube看到你的一期视频里面，当你在代码结尾`)`之前敲入`;`, emacs可以自动更正;的位置，请问这个是怎么实现的？我在你的emacs配置里没有找到相关信息。

例:  `|`是光标的位置
当我在光标处敲`;`

```
call('some value'|)
```

自动更正为:

```
call('some value');
```

谢谢

**Comment by zilongshanren** [comment]
@danielwuz 

不是自动更正 分号的位置啦，是在行尾插入分号：

```
(defun zilongshanren/insert-semicolon-at-the-end-of-this-line ()
  (interactive)
  (save-excursion
    (end-of-line)
    (insert ";")))

```

**Comment by zilongshanren** [comment]
`(bind-key* "s-;" 'zilongshanren/insert-semicolon-at-the-end-of-this-line)`

**Comment by danielwuz** [comment]
好的，已经加入我的配置，谢谢！
