### ISSUE TITLE
Font not available ...

### ISSUE THREAD

**Issue by mydearxym** [zilongshanren/spacemacs-private#23]
山人你好。
我安装好你的配置后报错 

``` bash
(Spacemacs) Error in dotspacemacs/user-config: Font not available: #<font-spec nil nil Source\ Code\ Pro nil nil nil nil nil 14 nil nil nil ((:name . "Source Code Pro:pixelsize=14") (user-spec . "Source Code Pro:pixelsize=14"))>
```

我已经在系统上安装了 [Source Code Pro字体](https://github.com/adobe-fonts/source-code-pro)
 Emacs版本为24.5.1，spacemacs版本为0.105.1

**Comment by zilongshanren** [comment]
@mydearxym  你要看看是否字体真的有安装成功，通过Font Book查看一下

**Comment by mydearxym** [comment]
@zilongshanren   谢谢回复 ， 我用 Font Book 手动安装一遍， 问题解决了。用 brew 安装貌似不起作用。
