### ISSUE TITLE
gulpjs没有安装成功？

### ISSUE THREAD

**Issue by xzyyjy** [zilongshanren/spacemacs-private#25]
installing package: gulpjs@guanghui... [1/1]
An error occurred while installing gulpjs (error: (wrong-type-argument stringp nil))

**Comment by xzyyjy** [comment]
难道是因为我注释了一些layers，使得一些文件没有下载？我也不想用gulpjs，可以在Emacs启动时不load它吗？

**Comment by zilongshanren** [comment]
@xzyyjy 你可以注释掉。。。 没安装成功可能是网络的问题吧，我一直在用gulp-js啊
