### ISSUE TITLE
emacsclient没有加载中文字体设置

### ISSUE THREAD

**Issue by ghost** [zilongshanren/spacemacs-private#26]
为了得到更快的启动速度,我打开了spacemacs的后台服务器,即在.spacemacs文件中设置

```
dotspacemacs-persistent-server t
```

然后按照chinese layer的readme, 在.spacemacs文件中 dotspacemacs/user-config ()这一段里加入

```
(spacemacs//set-monospaced-font "Source Code Pro" "Droid Sans Fallback" 16 20)
```

在terminal中用emacs启动中文字体没有问题
但使用emacsclient打开文件时中文字体变成了ubuntu默认的ukai
请问如何设置能够解决这个问题

谢谢!

**Comment by zilongshanren** [comment]
@xyk198307  这个问题最好去spacemacs官方仓库问一下，我也不是很清楚。

**Comment by zilongshanren** [comment]
建议去  emacs-china.org 提问和社区一起讨论
