### ISSUE TITLE
c++ company 后端

### ISSUE THREAD

**Issue by scloudyy** [zilongshanren/spacemacs-private#27]
山人你好，我看到你把ycmd的layer注释掉了，所以想请问一下你现在写c++代码时使用的company后端是什么？这样做有什么好处？

**Comment by zilongshanren** [comment]
@scloudyy  现在我基本上不怎么写c++了，所以注释掉了。
我现在用的是`company-gtags`来补全函数，前提要先生成gtags，然后keyword补全用的`company-daabrev`和`company-code`。

好处是速度快，稳定。精确的语义补全Emacs还是比不过IDE，此时我会优先使用IDE.

**Comment by yinchunlong** [comment]
请问下company-gtags支持lua吗, gtags --gtagslabel=ctags这样生成gtags后, 补全没用啊, 导航倒是可以, 谢谢山人指导~

**Comment by zilongshanren** [comment]
gtags 貌似不支持 lua，推荐使用 ctags，我现在基本不使用 gtags 了。 @yinchunlong
