### ISSUE TITLE
Sched.2x 是什么意思？

### ISSUE THREAD

**Issue by jcppython** [zilongshanren/spacemacs-private#28]
在org agenda view中，有个显示条目（Sched. 2x），不知道什么意思？。。

![screenshot from 2016-01-14 11 21 31](https://cloud.githubusercontent.com/assets/5669903/12314988/fab5b25e-bab0-11e5-8a03-93b335c7e0e5.png)

**Comment by zilongshanren** [comment]
@jcppython 就是你没有完成，因为你没有把它Done，每过一天都会+1，变成3x. 4x. nx..
