### ISSUE TITLE
support react develop in web-mode ?

### ISSUE THREAD

**Issue by mydearxym** [zilongshanren/spacemacs-private#29]
山人你好，现在的配置似乎不支持 react.js（ jsx语法 ） 的开发：

spacemacs:
![image](https://cloud.githubusercontent.com/assets/6184465/12533918/f35bd13a-c27d-11e5-8db1-fcf3f2f9128d.png)

我按照[这个方法](http://cha1tanya.com/2015/06/20/configuring-web-mode-with-jsx.html)进行设置，但总是报错，不知道加在哪里最合适呢？

我一直在用vim， vim 中显示没有问题：
![image](https://cloud.githubusercontent.com/assets/6184465/12533944/033999f6-c27f-11e5-8a06-e6c03294489f.png)

**Comment by zilongshanren** [comment]
@mydearxym 
我没有写 react-js，你可以去 https://emacs-china.org 上面发帖，好像 @codefalling 同学有在玩 react

**Comment by mydearxym** [comment]
@zilongshanren  谢谢，spacemacs 自带一个 react-mode 勉强可以用。
