### ISSUE TITLE
lua 的相关配置，怎么补全标准库？？

### ISSUE THREAD

**Issue by yinjun322** [zilongshanren/spacemacs-private#3]

**Comment by zilongshanren** [comment]
Lua的标准库？

**Comment by yinjun322** [comment]
对啊，刚刚用emacs，以前用Vim到还好，补全和文件管理都能配置

emacs本来刚用，就直接上spacemacs了，配置就头大了，也没什么中文资料可以参考的

**Comment by zilongshanren** [comment]
@yinjun322  
据我所知， Emacs目前并没有很好的可以补全 Lua 标准库的插件，但是其实要写一个这样的插件也很简单。

你可以用 company-mode 来补全。

**Comment by yinjun322** [comment]
3q
原来没有现成，那我再看看文档，然后自己搞个吧

还有个问题 emacs 有类似 NERDTree 这里的文件管理 插件吗？
dired 不怎么习惯。。

**Comment by zilongshanren** [comment]
@yinjun322 

spacemacs 自带 speedbar 啊

**Comment by yinjun322** [comment]
3q，去研究研究
回复好快啊
