### ISSUE TITLE
显示persp-mode错误

### ISSUE THREAD

**Issue by ghost** [zilongshanren/spacemacs-private#30]
zilongshanren 好，请教个问题：
我按照你的说明进行配置，显示下面的错误：
Error (use-package): persp-mode :init: Symbol's function definition is void: persp-mode
不知道是怎么回事，帮忙解答一下吧。谢谢！
另外，那个slack需要翻墙吗？我加不上去啊？

**Comment by zilongshanren** [comment]
@lxeg0429 
需要翻墙，可能是你的package下载失败，建议翻墙后再试试。

**Comment by ghost** [comment]
@zilongshanren 
我这就是翻墙安装的， 应该不是翻墙的问题。
下面是安装后显示的文字：
Warning (:warning): : `lexical-binding' at end of file unreliable
Error (use-package): persp-mode :init: Symbol's function definition is void: persp-mode
Warning (initialization): An error occurred while loading`e:/Software/Tools/Total Commander/Software/Emacs/Home/.emacs.d/init.el':

error: The directory `~/.emacs.d/server' is unsafe

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.

**Comment by chunhuitrue** [comment]
我安装了几次，也会出现这个错误。用emacs --insecure启动。或者先去elpa目录删除这个包。再重新启动。多试几次就好了。

**Comment by woshahua** [comment]
this fault always happen, when you run spacemacs under windows. And I think its a git problem. Use your cygwin upgrade git and install some useful tools of git(search git in cygwin installer), then it works in my case.
