### ISSUE TITLE
"chinese layer" and "git 依赖"

### ISSUE THREAD

**Issue by ghost** [zilongshanren/spacemacs-private#31]
子龙山人好：
在使用你的配置时，出现了点问题，请教一下。我自己在网上找了一个五笔的字体库，替换掉原来有wb.txt，可以用，但是有个别字打不出来，不知道是什么原因。
另外，陈斌的配置里有个特点是：去掉了git依赖，不知道在spacsmecs里如何实现这个功能，还请赐教。
谢谢！

lxeg0429

**Comment by zilongshanren** [comment]
那个Emacs内置五笔输入法我已弃坑，bug太多，有时候会卡机。。。

去掉git依赖，具体你指的是可以离线安装melpa包么？

**Comment by zilongshanren** [comment]
建议去  emacs-china.org 提问和社区一起讨论
