### ISSUE TITLE
是否考虑加csharp的layer吗？

### ISSUE THREAD

**Issue by wulei** [zilongshanren/spacemacs-private#32]
查找了一下c#的emacs相关支持，使用ominisharp是一个方案，是否能考虑加入？
spacemacs本身也有csharp版本，也是需要Omnisharp server
有想法使用emacs作为editor

**Comment by zilongshanren** [comment]
@wulei 
因为我没写csharp，所以暂时不会加。不过官方的c# layer貌似有吧。

**Comment by wulei** [comment]
@zilongshanren csharp已经ok了

有个问题询问一下，你是否在进入spacemacs加载包完毕后会卡一段时间？但是我看所有的package已经加载完毕了
