### ISSUE TITLE
evil的visual模式下插入列失败

### ISSUE THREAD

**Issue by XiaoLiuAI** [zilongshanren/spacemacs-private#34]
你好. 我安装了你的配置后,evil的visual模式下标记column之后进行列插入失败.请问是不是跟你所使用的某个包冲突了?

**Comment by zilongshanren** [comment]
@XiaoLiuAI  不是，因为我在insert state下面用了emacs state，我fix一下。

**Comment by zilongshanren** [comment]
@XiaoLiuAI 
现在更新一下我的最新配置就好啦
