### ISSUE TITLE
字符显示的问题

### ISSUE THREAD

**Issue by XiaoLiuAI** [zilongshanren/spacemacs-private#35]
你好

这一行中的图标字符在我的emacs中不能显示.

``` elisp
  (setq org-bullets-bullet-list '("🐉" "🐠" "🐬" "🐤")))
```

请问你是用了什么特殊设置把它们显示出来的?还是说你的emacs自动就能显示这些字符?

**Comment by zilongshanren** [comment]
@XiaoLiuAI 
Mac电脑才可以显示。。。

**Comment by XiaoLiuAI** [comment]
我用的就是mac.homebrew安装的emacs。那些字符在终端下都可以显示，但是emacs里面就不行。你是怎么装的emacs？用了什么编译选项？

**Comment by zilongshanren** [comment]
@XiaoLiuAI 
我是按照spacemacs官方推荐的方法安装 的，也是用brew安装的。

**Comment by zilongshanren** [comment]
@XiaoLiuAI  必须安装emacs mac port  https://github.com/railwaycat/emacs-mac-port

**Comment by XiaoLiuAI** [comment]
@zilongshanren 多谢！
