### ISSUE TITLE
fcitx--active-p-proc: Searching for program: no such file or directory, fcitx-remote

### ISSUE THREAD

**Issue by huangyingwen** [zilongshanren/spacemacs-private#36]
zilongshanren 好，请教个问题：
我按照你的说明进行配置，显示下面的错误：
fcitx--active-p-proc: Searching for program: no such file or directory, fcitx-remote
是不是需要安装什么东西？帮忙看看，谢谢！

**Comment by zilongshanren** [comment]
@huangyingwen 
安装 https://github.com/CodeFalling/fcitx-remote-for-osx 这个
