### ISSUE TITLE
使用您的spacemacs-private 无法启动

### ISSUE THREAD

**Issue by maozhiyong** [zilongshanren/spacemacs-private#37]
Warning (initialization): An error occurred while loading `/Users/maozhiyong/.emacs.d/init.el':

Args out of range: #<killed buffer>, 131585, 156647

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.

**Comment by zilongshanren** [comment]
@maozhiyong  使用emacs --debug-init看看报啥错吧。

**Comment by maozhiyong** [comment]
Debugger entered--Lisp error: (error "Format specifier doesn't match argument type")
  message("Your version of Emacs (%s) is too old. Spacemacs requires Emacs version %d or above." "22.1.1" "24.3")
  (if (not (version<= spacemacs-emacs-min-version emacs-version)) (message (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %d or above.") emacs-version spacemacs-emacs$
  eval-buffer(#<buffer  *load*> nil "/Users/maozhiyong/.emacs.d/init.el" nil t)  ; Reading at buffer position 1076
  load-with-code-conversion("/Users/maozhiyong/.emacs.d/init.el" "/Users/maozhiyong/.emacs.d/init.el" t t)
  load("/Users/maozhiyong/.emacs.d/init" t t)
  #[nil "^H\205\276^@   \306=\203^Q^@\307^H\310Q\202A^@ \311=\2033^@\312\307\313\314#\203#^@\315\202A^@\312\307\313\316#\203/^@\317\202A^@\315\202A^@   \320=\203=^@\321\202A^@\307^H\322Q^Z\323^S\324\n\32$
  command-line()
  normal-top-level()

**Comment by zilongshanren** [comment]
@maozhiyong 你的emacs版本太老了。。 更新一下吧。

**Comment by zilongshanren** [comment]
至少24.4+

**Comment by maozhiyong** [comment]
我看了下 我这个emacs是24.5的诶

**Comment by zilongshanren** [comment]
@maozhiyong 
你是什么平台？ 用的哪个版本的Emacs? 使用的spacemacs是哪个版本？

**Comment by maozhiyong** [comment]
我的是osx 平台，24.5的emacs 。spacemacs是根据您的的Readme步骤git clone https://github.com/syl20bnr/spacemacs.git ~/.emacs.d 这么得到的

**Comment by zilongshanren** [comment]
@maozhiyong 
你有checkout出develop分支吗？ 我也是osx哦，一点问题也没有。不过我用的是emacs-mac port，而不是GNU Emacs， 不过这个问题不大。

**Comment by maozhiyong** [comment]
git checkout --track origin/develop使用后显示的是
fatal: A branch named 'develop' already exists.

**Comment by zilongshanren** [comment]
@maozhiyong  建议对照官方仓库的README的installation部分再试一下哦。。 可以先考虑不用我的配置，看spacemacs是否可以跑起来。

**Comment by maozhiyong** [comment]
好的，我把.emacs.d 与 .spacemacs.d删除 再安装一下试试。谢谢您的帮助

**Comment by maozhiyong** [comment]
您好，现在emacs spacemacs可以打开了，但是在打开文件的时候，Searching for program:no such file or directory,fcitx-remote。

**Comment by maozhiyong** [comment]
您好，可以打开了，我将.spacemacs/init.el 里面 将chinese:variable 这里的都删除掉，估计我的电脑不支持现在。然后只使用chinese，就可以正常使用了。另外，我是先下载spacemacs的文件，正常打开后，将.spacemacs配置备份掉，接着git clone您的.spacemacs.d的文件，然后就可以打开了

**Comment by zilongshanren** [comment]
@maozhiyong  你需要安装fcitx-remote

**Comment by maozhiyong** [comment]
好了 谢谢您，现在可以正常运行了。
