### ISSUE TITLE
不可见字符的显示问题

### ISSUE THREAD

**Issue by gemire** [zilongshanren/spacemacs-private#40]
你好，我在windows下使用您的配置，emacs版本为25.0.92, spacemacs版本为0.105.14.
在使用过程中，发现一些不可见字符会显示出来。如下图所示：
![image](https://cloud.githubusercontent.com/assets/3426489/13747709/91b1b448-ea34-11e5-952e-626d5009800e.png)
![image](https://cloud.githubusercontent.com/assets/3426489/13747741/bcfb4128-ea34-11e5-8d7c-d4798db83e1d.png)
在使用您的配置之前是没有这个问题的, 在网上也没有找到相关的资料，请问该如何不显示这些隐藏字符(如图中的tab键，^M等)？

**Comment by bennyyip** [comment]
^M是windows下的换行符
Unix用LF, Windows用CRLF
可以用下面的函数把\r去掉

``` elisp
(defun dos2unix ()
  "Replace DOS eolns CR LF with Unix eolns CR"
  (interactive)
  (goto-char (point-min))
  (while (search-forward "\r" nil t) (replace-match "")))
```

至于tab的问题我只有在Makefile下看到过,我还以为是一个特性..
楼主你在哪些mode见过这样的tab

**Comment by gemire** [comment]
1. 这个函数在spacemacs的 layers/+distribution/spacemacs-base/funcs.el 里面已经有了，但实现不太一样，我把这里面的函数改为你这个，没有去掉 ^M 字符
2. 在Java/l mode下会出现这个tab

**Comment by bennyyip** [comment]
@gemire 我用自带的那个反而无效,用这个就能去掉

**Comment by gemire** [comment]
@bennyyip 我把你的spacmesmacs配置checkout后，在用的时候发现这些^M还在。可能还有其他地方的问题，我再看看

**Comment by zilongshanren** [comment]
@gemire 

please try:

```
(defun remove-dos-eol ()
  "Do not show ^M in files containing mixed UNIX and DOS line endings."
  (interactive)
  (setq buffer-display-table (make-display-table))
  (aset buffer-display-table ?\^M []))
```

**Comment by zilongshanren** [comment]
@gemire 如果要去掉tab，你可以`M-x whitespace-mode` 来关闭

**Comment by gemire** [comment]
@zilongshanren 
1. tab键用上面的方法可以解决。
2. 关于换行符的问题，我把配置同步了以后，^M还在，问题没有解决。
3. 我还试了把这个函数加到init.el中user-config下，^M仍然在。
4. 我看了下出现^M文件的换行符，其为CRLF, 换行符为LF的文件打开则没有^M符号。

**Comment by zilongshanren** [comment]
@gemire 
这个函数是要调用的。。。只加到user-config下面是没用的

**Comment by bennyyip** [comment]
@gemire  我那个函数的作用是调用之后把当前buffer的/r删掉,光添加到配置也是没有用的

**Comment by gemire** [comment]
@zilongshanren @bennyyip  自己刚开始用spacemacs, 对其中的机制还不是很了解，问题已经解决，多谢!
