### ISSUE TITLE
set evil-escape-key-sequence not work

### ISSUE THREAD

**Issue by mydearxym** [zilongshanren/spacemacs-private#41]
amazing work !
base on the spacemacs docs , evil-escape-key-sequence can be set to custom keys:
![image](https://cloud.githubusercontent.com/assets/6184465/13863687/955be6a0-ecd6-11e5-8f98-ead520a981b2.png)

but  this config is not work in your config 

![image](https://cloud.githubusercontent.com/assets/6184465/13863706/b7afb574-ecd6-11e5-92bd-f718dc070db2.png)

**Comment by zilongshanren** [comment]
@mydearxym 
I have excluded `evil-escape` package, because it conflicts with `lispy`, so please remove `evil-escape` from `dotspacemacs-excluded-packages` in your `.spacemacs` file.

**Comment by mydearxym** [comment]
@zilongshanren thanks for the hint .
