### ISSUE TITLE
配置不生效

### ISSUE THREAD

**Issue by iuunhao** [zilongshanren/spacemacs-private#42]
您好，我按着您的README操作，然后看您的视频教程，发现您的视频里面的有的操作，配置里面并没有，比如再finder里面打开文件、还有最后说的那个代替tree的功能.

**Comment by zilongshanren** [comment]
@iuunhao  finder里面打开文件是什么？ 是用finder打开文件所在目录吧？

另外，你说的tree指的是？我的配置从我录制视频开始，中间已经有不少变化了，另外spacemacs的官方配置也有不少修改，所以会出现一些不一致的情况。。。

**Comment by iuunhao** [comment]
问题我解决了，我clone了spceemacs之后之后安装了插件，再clone您的配置，就不会自动安装了，我把您的所有配置clone下来之后，打开emacs之后安装了之后就正常了。配置很棒，我很喜欢，不过，我发现您的配置是最新的，但是您之前的视频教程应该是之前的配置，所以有个别的快捷键并不使用，不过不影响使用，看了您的配置，学到了很多东西，很感谢您给我们提供这样棒的配置。

**Comment by zilongshanren** [comment]
@iuunhao  不客气
