### ISSUE TITLE
子龙，问一下，我用了你的layer之后，出现下面错误，我刚开始用emacs，找了一下没找到错误，能帮忙看一下吗

### ISSUE THREAD

**Issue by lengyueyang** [zilongshanren/spacemacs-private#45]
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `dired-mode-map':
- `dired-do-chgrp' originally mapped on`G'
  (Spacemacs) Warning: Auto-evilication could not remap these functions in map `org-agenda-mode-map':
- `org-agenda-next-line' originally mapped on`C-n'
  (Spacemacs) Warning: Auto-evilication could not remap these functions in map `org-agenda-mode-map':
- `org-agenda-toggle-time-grid' originally mapped on`G'
  (Spacemacs) Warning: Auto-evilication could not remap these functions in map `org-agenda-mode-map':
- `org-agenda-filter-remove-all' originally mapped on`|'
  (Spacemacs) Warning: Auto-evilication could not remap these functions in map `org-agenda-mode-map':
- `org-agenda-filter-by-tag-refine' originally mapped on`\'
  Starting new Ispell process /usr/bin/aspell with default dictionary...

**Comment by zilongshanren** [comment]
@lengyueyang  我目前也有这个警告，不过好像并不影响使用。。。 把我的layer去掉警告就消除了吗？

**Comment by lengyueyang** [comment]
嗯，子龙还没有睡啊
我的org-mode在agenda窗口，到TODO任务，按ENTER会打开另外一个窗口，设置完后不会回到agenda窗口，之前看你的视频可以回去，我之前也可以，一月份更新后就不行了，不知道是不是我设置的问题

**Comment by zilongshanren** [comment]
@lengyueyang  我好像是在agenda里面按TAB键去进入另一个窗口。。

**Comment by lengyueyang** [comment]
谢谢了，子龙，我先这么用着
