### ISSUE TITLE
org-babel 的问题

### ISSUE THREAD

**Issue by a5corpii** [zilongshanren/spacemacs-private#46]
zilongshanren 你好，
我使用您的配置 .spacemacs.d/ 和 org-babel 时，报错，如下：

> Error in dotspacemacs/user-config: Invalid function: org-babel-header-args-safe-fn

我在 user-config 里加入了这些：

```
  (org-babel-do-load-languages
    'org-babel-load-languages
    '((C . t)
      (ditaa . t)
      (dot . t)
      (latex . t)
      (octave . t)
      (org . t)
      (perl . t)
      (python . t)
      (R . t)
      (ruby . t)
      (sh . t)
      (sqlite . t)
      ))
  (setq org-confirm-babel-evaluate nil)

```

并且在 configuration-layer 里加入了 ess(emacs speak statistics)

其他的只有行号的显示等改动，应该不影响。

**Comment by zilongshanren** [comment]
@erstern  你可以参考一下 https://github.com/syl20bnr/spacemacs/issues/3314

**Comment by a5corpii** [comment]
Thx!
我的 .emacs.d/elpa 里找不到 org-plus-contrib，只有 org 是怎么回事？其他倒是都一样。
仍然解决不了。

**Comment by zilongshanren** [comment]
@erstern  你可能把org-plus-contrib给exclude掉了，检查一下.spacemacs.d/init.el里面的exclude掉的package吧。

**Comment by a5corpii** [comment]
是的，excluded-packages 裏面有 org-plus-contrib。
我下午看了一下，20160328的org沒有問題，20160404的版本就不行了。
我再試試。

**Comment by zilongshanren** [comment]
建议去  emacs-china.org 提问和社区一起讨论
