### ISSUE TITLE
与auto complete相关的错误

### ISSUE THREAD

**Issue by tianyuqi123** [zilongshanren/spacemacs-private#47]
你好，我在装auto compelet时出现了以下错误
File mode specification error: (void-function yas--load-pending-jits)
yas-minor-mode: Symbol's function definition is void: yas--load-pending-jits
Error in post-command-hook (yas--post-command-handler): (void-function yas--post-command-handler)
Error in post-command-hook (yas-global-mode-check-buffers): (void-function yas--load-pending-jits)
请问这要怎么解决，谢谢

**Comment by zilongshanren** [comment]
@tianyuqi123  你看看 `.emacs.d` 目录下面是否安装了yasnippets，如果安装了，你试试重新byte-compile。

**Comment by tianyuqi123** [comment]
M-x byte-recompile-dirctory rep .emacs.d
还是一样的错误
我是小白，不太懂，这样做对吗

**Comment by tianyuqi123** [comment]
@zilongshanren

**Comment by zilongshanren** [comment]
@tianyuqi123  不对。。 是M-x byte-recompile-directory ~/.emacs.d/elpa/yasnippets-xxxx/

**Comment by tianyuqi123** [comment]
@zilongshanren 还是一样==

**Comment by tianyuqi123** [comment]
@zilongshanren 还有什么办法吗？我google也没找到解决办法，只要装了auto completion就会出错

**Comment by zilongshanren** [comment]
@tianyuqi123  那你有在.emacs.d/elpa/目录下面找到yasnippet目录吗？

**Comment by tianyuqi123** [comment]
@zilongshanren 有

**Comment by zilongshanren** [comment]
@tianyuqi123  你的Emacs版本是？另外，你是用的我配置的最新版本吗？

**Comment by tianyuqi123** [comment]
@zilongshanren 24.5.1，我没有用你的配置，我只是在.spacemacs中加了auto completion，不用auto   completion是没有错误的，我是ubuntu系统

**Comment by zilongshanren** [comment]
@tianyuqi123  你是用的develop分支吗？ 建议你去spacemacs那里提issue

**Comment by tianyuqi123** [comment]
@zilongshanren 是develop分支，好的，谢了

**Comment by tianyuqi123** [comment]
@zilongshanren 搞定了，把yasnippet删掉，然后它自动重装就好了，是因为版本问题吗？

**Comment by zilongshanren** [comment]
@tianyuqi123  对的，是版本问题
