### ISSUE TITLE
子龙，能否提供你的org mode的配置？

### ISSUE THREAD

**Issue by ghost** [zilongshanren/spacemacs-private#49]
Hi，
    看了你的orgmode视频，感觉你用org mode来做gtd流程非常好，能否提供你的orgmode详细配置？主要是gtd、capture和用orgmode写博客的配置。

**Comment by zilongshanren** [comment]
@Yufael  我的配置就在这个仓库里面呀

**Comment by ghost** [comment]
额，找到了，原来在package.el里。我老想着找org开头的文件了- -
