### ISSUE TITLE
Mac 保存时不能自动加密

### ISSUE THREAD

**Issue by zealinux** [zilongshanren/spacemacs-private#5]
截取了你的私人代码
https://github.com/zilongshanren/spacemacs-private/blob/develop/layers/zilongshanren/packages.el#L958
这下面几行，

在我Mac上设置成`secret`tag，保存时没有自动加密。
另外，我如果`org-encryt-entry`是可以加密的，（要输入两次密码）

**Comment by zilongshanren** [comment]
我是设置完`secret` tag后就会自动提示我输入密码
