### ISSUE TITLE
当前文件下自动补全如何关闭？

### ISSUE THREAD

**Issue by panlei7** [zilongshanren/spacemacs-private#50]
对于写代码来说，自动补全很方便；可有时候要写一些东西，比如博客之类，输着单词就出现补全框，很打扰思路，这时候有没有办法临时关闭自动补全，比如直接按某些键？

**Comment by zilongshanren** [comment]
@panlei7  `SPC t a` 关闭补全呀？

**Comment by panlei7** [comment]
原来这么简单，我google了好久……谢谢

**Comment by zilongshanren** [comment]
@panlei7  😄  issue我关了。
