### ISSUE TITLE
去除跳转效果的问题

### ISSUE THREAD

**Issue by mydearxym** [zilongshanren/spacemacs-private#51]
请教一下怎么除去下面这种跳转后有一个白色渐变然后消失的效果呢？
初看挺好玩，久了实在是眼花并且影响注意力。
文档里一直没有找到相关配置。。。

![test](https://cloud.githubusercontent.com/assets/6184465/14487893/cd6cf37e-0197-11e6-9c1f-dbd91c680fcd.gif)

**Comment by zilongshanren** [comment]
@mydearxym  exclude `beacon` package...

**Comment by mydearxym** [comment]
thanks very much !
