### ISSUE TITLE
Error When Starting Spacemacs

### ISSUE THREAD

**Issue by junfeiwa** [zilongshanren/spacemacs-private#53]
Error in dotspacemacs/user-config: Symbol's function definition is void: spacemacs|define-transient-state
Sorry I cannot type Chinese on this laptop ;)

**Comment by zilongshanren** [comment]
@junfeiwa  maybe some packages not installed properly.. try to delete all the contents under `~/.emacs.d/elpa` and restart spacemacs...

You might need to setup a VPN for Emacs...
