### ISSUE TITLE
export latex source to html via org-mode

### ISSUE THREAD

**Issue by a5corpii** [zilongshanren/spacemacs-private#54]
Hello,
我用 org-mode 整理了一些東西，然後想再轉一份 html 版。
有些公式，比如同時上下标、開根號，org-mode 本身顯示效果不好（或者我不知道更好的方式），用到了 latex 代碼。
這些插入的 latex source，比如：

```
#+BEGIN_SRC latex
$ x̄ = ( Σ^n_{i=1} X_i) / n $
#+END_SRC
```

在 .org 文件裏顯示很好，但是 C-c C-e h h 之後，在 .html 裏就看不到了。

查到的某一個方法，添加其他配置之前，需要先在 Emacs 的配置文件裏加入：

```
  (require 'org-latex)                                 
  (unless (boundp 'org-export-latex-classes)           
    (setq org-export-latex-classes nil))               
  (add-to-list 'org-export-latex-classes               
               '("article"                             
                 "\\documentclass{article}"            
                 ("\\section{%s}" . "\\section*{%s}")))
```

但是 spacemacs 報錯，找不到 org-latex 。

請問 org-latex 對應的是哪個 layer？
或者還有哪些可以把 org-mode 裏的 LaTeX source block 轉換爲 html 的好的解決方案？

謝謝！

**Comment by zilongshanren** [comment]
@erstern  

latex 我也不是很熟悉，你可以去  emacs-china.org 发帖讨论，论坛有不少人会玩 latex.

**Comment by zilongshanren** [comment]
建议去  emacs-china.org 提问和社区一起讨论
