### ISSUE TITLE
无法切换Them

### ISSUE THREAD

**Issue by nick357** [zilongshanren/spacemacs-private#55]
<Space>+T+s 选择spacemacs-light不起效果。
另外请教下在.spacemacs.d/custom.el配置中怎么设定theme为spacemacs-light。
注平台：windows10+GNU Emacs 24.4.1 (x86_64-w64-mingw32)

**Comment by nick357** [comment]
我注释掉custom.el的75行
'(default ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :background "#272822")) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C"))))
就能正常切换了，这个大概是什么作用呢，好像是根据支持的颜色数设定了背景和前景色。
这样导致了切换theme的背景和前景色不起效果导致的。

**Comment by zilongshanren** [comment]
@nick357  这应该是我的配置的 bug。。。 遗留的代码，我也不记得是干嘛的了。。

**Comment by nick357** [comment]
@zilongshanren 好的，非常感谢你的回复和配置，使得一个新手能简单就使用上emacs。希望做得越来越好。

**Comment by zilongshanren** [comment]
欢迎多去 emacs-china.org上交流，issue 我先关了。
