### ISSUE TITLE
anaconda-mode报错

### ISSUE THREAD

**Issue by tianxingyzxq** [zilongshanren/spacemacs-private#56]
打开python文件，在anaconda-mode中出现以下错误：
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ImportError: No module named pkg_resources
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: No module named pip
但是pip和pkg_resources模块都有的，message中报错为：
Can not install `anaconda-mode' server

有人碰到类似的问题吗，系统ubuntu16.04，emacs版本为24.5.1

**Comment by zilongshanren** [comment]
@tianxingyzxq  没有遇到类似的问题。。。

**Comment by zilongshanren** [comment]
https://github.com/proofit404/anaconda-mode/issues/114

**Comment by zilongshanren** [comment]
不好意思，看错了，以为是 mac. ubuntu 的话，建议去作者的仓库提 issue.

**Comment by zilongshanren** [comment]
建议去  emacs-china.org 提问和社区一起讨论。
