### ISSUE TITLE
无法识别dos换行格式文件，显示^M

### ISSUE THREAD

**Issue by nick357** [zilongshanren/spacemacs-private#57]
如题，注释掉.spacemacs.d\layers\zilongshanren\packages.el 第135行
(setq inhibit-eol-conversion t) 
这句后能正常识别dos换行文件。

**Comment by zilongshanren** [comment]
@nick357  注释掉就不显示 ^M 了么？

**Comment by zilongshanren** [comment]
@nick357  我这个设置是禁止换行符转换的。。。

**Comment by nick357** [comment]
对的，你可以用个dos换行的文件试试。我看之前也有人提过类似bug。
1、用函数转换为unix换行的话，对dos换行文件没做到支持
2、调用隐藏eol的函数，在编辑的过程中，插入行是unix方式，会导致有两种换行的混乱
如果没有其他影响，建议注释掉这句。这样就能正常识别和编辑dos换行文件

**Comment by zilongshanren** [comment]
@nick357  好的， 感谢提醒。我把它注释掉吧。

**Comment by zilongshanren** [comment]
@nick357  已经修复，感谢。
