### ISSUE TITLE
powerline not update git branch info

### ISSUE THREAD

**Issue by mydearxym** [zilongshanren/spacemacs-private#58]
when switch branch using magit , the powerline git info not update

![image](https://cloud.githubusercontent.com/assets/6184465/14858121/66f1858e-0cd1-11e6-825e-7a870a9bea53.png)

or it's there a way to manually update it ?

**Comment by zilongshanren** [comment]
@mydearxym  
It's a know issue...  See https://github.com/syl20bnr/spacemacs/issues/2172

**Comment by mydearxym** [comment]
如此重要的 feature , 太遗憾了。。
