### ISSUE TITLE
关于按键绑定的一个问题

### ISSUE THREAD

**Issue by cosmicwalker** [zilongshanren/spacemacs-private#6]
山人你好，你在keybinding.el里写
(global-set-key (kbd "s-s") 'save-buffer)
(bind-key* "s-k" 'scroll-other-window-down)
(bind-key* "s-j"  'scroll-other-window)
请问s-s s-k s-j该怎么按？是字母s加字母s还是shift加字母s，但我在normal模式下试了两种都不行，所以很奇怪。

**Comment by zilongshanren** [comment]
s 在 mac 下面是 Command， 在 windows 上面是 Win 键，不过 Windows 上面有全局的按键绑定，所以按起来有问题。你可以换成别的。

**Comment by zilongshanren** [comment]
而且 Mac 上面的 command 也可以定义成 meta 键，windows 上面的 win 键也需要定义才可以变成 s.
s 即 super key。 @cosmicwalker
