### ISSUE TITLE
我想切换buffer, C-x的时候直接卡死?`SPC`+`b`没问题?

### ISSUE THREAD

**Issue by zengfengbo** [zilongshanren/spacemacs-private#63]
我想切换buffer, C-x的时候直接卡死?`SPC`+`b`没问题?为什么?

**Comment by zilongshanren** [comment]
我的并不会哦。。。 你的 Emacs 卡死之后，你在终端输入 :  `pkill -SIGUSR2 -i emacs` , 然后把 call stack 帖出来看看。

**Comment by zengfengbo** [comment]
我全屏之后又可用了.我再测试一下.

**Comment by zengfengbo** [comment]
没问题,可能是网络问题,启动之后一会网络不好的话会卡死.

**Comment by zengfengbo** [comment]
Debugger entered--entering a function:
- vr--after-change(1 5 0)  
  call-process("fcitx-remote" nil nil nil "-c")  
  fcitx--deactivate-proc()  
  fcitx--deactivate()  
  fcitx--prefix-keys-maybe-deactivate()  
  fcitx--prefix-keys-polling-function()  
  apply(fcitx--prefix-keys-polling-function nil)  
  byte-code("r\301\302H\303H\"\210)\301\207" [timer apply 5 6] 4)  
  timer-event-handler([t 22352 16900 678671 0.1 fcitx--prefix-keys-polling-function nil nil 107548])

**Comment by zilongshanren** [comment]
@zengfengbo  建议给 @cute-jumper 同学提 issue
