### ISSUE TITLE
archors in searchs

### ISSUE THREAD

**Issue by glimmercn** [zilongshanren/spacemacs-private#65]
在用你的config，发现search时，比如M-x 执行某个命令，或者C-h v找某个命令，搜索会自动加上^这个锚定。

对我这样刚接触emacs的人来说，一般会把^去掉。spacemacs的默认设置不是这样的。请问是需要改动哪里？

**Comment by zilongshanren** [comment]
```
    (setq ivy-initial-inputs-alist nil)
```

**Comment by zilongshanren** [comment]
@glimmercn  
更新信息请阅读作者的博客： http://oremacs.com/2016/01/06/ivy-flx/
