### ISSUE TITLE
helm-gtags and ycmd

### ISSUE THREAD

**Issue by glimmercn** [zilongshanren/spacemacs-private#67]
尝试用spacemacs做ide。

把helm-gtags添加到（setq guanghui-packages ）里面，不会自动安装。包括原来在guanghui这个layer里面的pacakge ycmd也不能自动安装。

手动用package-install安装完之后，重启后被自动删除。我想应该是dotspacemacs-delete-orphan-packages t引起的吧。

请问这是什么原因，谢谢。

**Comment by glimmercn** [comment]
试了一下，把dotspacemacs-delete-orphan-packages 设置成nil，问题依然存在。不知道毛病出在哪里。

**Comment by zilongshanren** [comment]
@glimmercn 
每一个在 （setq guanghui-packages ）里面定义的 package 要安装的话，都需要定义相应的函数，具体你可以看我的 layer 里面是怎么写的。

如果只想写一个 package 名字就安装 package，那么这个 package 应该写在

`dotspacemacs-additional-packages '()`

这个变量里面。 这个变量在 .spacemacs.d/init.el 里面有

**Comment by glimmercn** [comment]
原因是helm-gtags已经被包含在了c-c++ layer里面，而那个里面没有定义init-helm-gtags, 而只定义了post-init-helm-gtags。gtags并没有被安装。

我在guanghui layer的package.el里面加入了相应的init-helm-gtags function，并在里面use-package，就会报错。

把c-c++ layer里面的相关内容移除，就解决了问题。
