### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by qx** [zilongshanren/spacemacs-private#68]
@zilongshanren fcitx-remote is not avaiable,please check your fcitx installtion

**Comment by zilongshanren** [comment]
@qx  你可以把 fcitx 这个 package exclude 掉。

**Comment by qx** [comment]
https://github.com/CodeFalling/wiki/issues/2 @zilongshanren 找到解决办法了.
按照上面的地址安装了拼音输入,刚学emacs,这个不怎么懂.
在youtube上搜到你的视频,帮我省了很多功夫,谢谢.我也要吐槽一下国内的资料,中文的有用的视频太少了.
