### ISSUE TITLE
安装以后遇到2个问题。

### ISSUE THREAD

**Issue by gatspy** [zilongshanren/spacemacs-private#69]
Warning (:warning): : `lexical-binding' at end of file unreliable
Warning (fcitx.el):`fcitx-remote' is not avaiable. Please check your fcitx installtion.
使用山人的配置以后，安装完成遇到上面两个警告。

**Comment by zilongshanren** [comment]
因为你没有安装 fcitx-remote 的原因，我现在已经把这个从我的配置中移除了，你可以同步一下我的最新配置。

**Comment by gatspy** [comment]
谢谢山人~ 以解决
