### ISSUE TITLE
关于win10下安装及字体问题  Emacs版本为25.5，spacemacs版本为0.105.x

### ISSUE THREAD

**Issue by wzhe** [zilongshanren/spacemacs-private#7]
debug信息太多，贴在下面
安装后图中显示有两处错误。如下。
![qq 20151027234515](https://cloud.githubusercontent.com/assets/6120110/10763533/44110c3a-7d05-11e5-8851-e205058bc93b.png)
在monokai主题下部分中文字体无法显示，在别的主题是可以正常显示。在所有主题下标题前的图标均显示无法显示，显示的是如图中的方框。

**Comment by wzhe** [comment]
Debugger entered--returning value: nil
  (condition-case err (progn (hl-highlight-mode) (setq-default hl-highlight-save-file (concat spacemacs-cache-directory ".hl-save")) (evil-leader/set-key "hc" (quote hl-unhighlight-all-local) "hC" (quote hl-unhighlight-all-global) "hh" (quote hl-highlight-thingatpt-local) "hH" (quote hl-highlight-thingatpt-global) "hn" (quote hl-find-next-thing) "hN" (quote hl-find-prev-thing) "hr" (quote hl-restore-highlights) "hs" (quote hl-save-highlights))) ((debug error) (ignore (display-warning (quote use-package) (format "%s %s: %s" "hl-anything" ":init" (error-message-string err)) :error))))
  (progn (condition-case err (progn (hl-highlight-mode) (setq-default hl-highlight-save-file (concat spacemacs-cache-directory ".hl-save")) (evil-leader/set-key "hc" (quote hl-unhighlight-all-local) "hC" (quote hl-unhighlight-all-global) "hh" (quote hl-highlight-thingatpt-local) "hH" (quote hl-highlight-thingatpt-global) "hn" (quote hl-find-next-thing) "hN" (quote hl-find-prev-thing) "hr" (quote hl-restore-highlights) "hs" (quote hl-save-highlights))) ((debug error) (ignore (display-warning (quote use-package) (format "%s %s: %s" "hl-anything" ":init" (error-message-string err)) :error)))) (condition-case err (run-hooks (quote use-package--hl-anything--post-init-hook)) ((debug error) (ignore (display-warning (quote use-package) (format "%s %s: %s" "hl-anything" "post-:init hook" (error-message-string err)) :error)))))
  (if (condition-case err (run-hook-with-args-until-failure (quote use-package--hl-anything--pre-init-hook)) ((debug error) (ignore (display-warning (quote use-package) (format "%s %s: %s" "hl-anything" "pre-:init hook" (error-message-string err)) :error)))) (progn (condition-case err (progn (hl-highlight-mode) (setq-default hl-highlight-save-file (concat spacemacs-cache-directory ".hl-save")) (evil-leader/set-key "hc" (quote hl-unhighlight-all-local) "hC" (quote hl-unhighlight-all-global) "hh" (quote hl-highlight-thingatpt-local) "hH" (quote hl-highlight-thingatpt-global) "hn" (quote hl-find-next-thing) "hN" (quote hl-find-prev-thing) "hr" (quote hl-restore-highlights) "hs" (quote hl-save-highlights))) ((debug error) (ignore (display-warning (quote use-package) (format "%s %s: %s" "hl-anything" ":init" (error-message-string err)) :error)))) (condition-case err (run-hooks (quote use-package--hl-anything--post-init-hook)) ((debug error) (ignore (display-warning (quote use-package) (format "%s %s: %s" "hl-anything" "post-:init hook" (error-message-string err)) :error))))))
  (progn (if (condition-case err (run-hook-with-args-until-failure (quote use-package--hl-anything--pre-init-hook)) ((debug error) (ignore (display-warning (quote use-package) (format "%s %s: %s" "hl-anything" "pre-:init hook" (error-message-string err)) :error)))) (progn (condition-case err (progn (hl-highlight-mode) (setq-default hl-highlight-save-file (concat spacemacs-cache-directory ".hl-save")) (evil-leader/set-key "hc" (quote hl-unhighlight-all-local) "hC" (quote hl-unhighlight-all-global) "hh" (quote hl-highlight-thingatpt-local) "hH" (quote hl-highlight-thingatpt-global) "hn" (quote hl-find-next-thing) "hN" (quote hl-find-prev-thing) "hr" (quote hl-restore-highlights) "hs" (quote hl-save-highlights))) ((debug error) (ignore (display-warning (quote use-package) (format "%s %s: %s" "hl-anything" ":init" ...) :error)))) (condition-case err (run-hooks (quote use-package--hl-anything--post-init-hook)) ((debug error) (ignore (display-warning (quote use-package) (format "%s %s: %s" "hl-anything" "post-:init hook" ...) :error)))))) (let ((now (current-time))) (message "%s..." "Loading package hl-anything") (prog1 (if (not (require (quote hl-anything) nil (quote noerror))) (ignore (message (format "Could not load %s" (quote hl-anything)))) (let ((now (current-time))) (message "%s..." "Configuring package hl-anything") (prog1 (progn (if ... ...) t) (let (...) (if ... ... ...))))) (let ((elapsed (float-time (time-subtract ... now)))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Loading package hl-anything" elapsed) (message "%s...done" "Loading package hl-anything"))))))
  spacemacs/init-hl-anything()
  funcall(spacemacs/init-hl-anything)
  (let* ((pkg-name (eieio-oref pkg (quote :name))) (owner (eieio-oref pkg (quote :owner))) (owner-layer (object-assoc owner :name configuration-layer--layers)) (disabled-for-layers (eieio-oref owner-layer (quote :disabled-for)))) (spacemacs-buffer/message (format "Configuring %S..." pkg-name)) (mapc (function (lambda (layer) (if (memq layer disabled-for-layers) (spacemacs-buffer/message (format "  -> ignored pre-init (%S)..." layer)) (spacemacs-buffer/message (format "  -> pre-init (%S)..." layer)) (condition-case err (funcall (intern ...)) ((quote error) (configuration-layer//set-error) (spacemacs-buffer/append ...)))))) (eieio-oref pkg (quote :pre-layers))) (spacemacs-buffer/message (format "  -> init (%S)..." owner)) (funcall (intern (format "%S/init-%S" owner pkg-name))) (mapc (function (lambda (layer) (if (memq layer disabled-for-layers) (spacemacs-buffer/message (format "  -> ignored post-init (%S)..." layer)) (spacemacs-buffer/message (format "  -> post-init (%S)..." layer)) (condition-case err (funcall (intern ...)) ((quote error) (configuration-layer//set-error) (spacemacs-buffer/append ...)))))) (eieio-oref pkg (quote :post-layers))))
  configuration-layer//configure-package([eieio-class-tag--cfgl-package hl-anything spacemacs nil (zilongshanren) elpa nil nil])
  (cond ((eq (quote dotfile) (eieio-oref pkg (quote :owner))) (configuration-layer//activate-package pkg-name) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//activate-package pkg-name) (configuration-layer//configure-package pkg)))
  (cond ((eieio-oref pkg (quote :excluded)) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg (quote :owner))) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) (t (let ((location (eieio-oref pkg (quote :location)))) (cond ((stringp location) (if (file-directory-p location) (setq load-path (cons ... load-path)) (spacemacs-buffer/warning "Location path for package %S does not exists (value: %s)." pkg location))) ((and (eq (quote local) location) (eq (quote dotfile) (eieio-oref pkg ...))) (setq load-path (cons (file-name-as-directory ...) load-path))) ((eq (quote local) location) (let* ((owner ...) (dir ...)) (setq load-path (cons ... load-path)) (setq load-path (cons ... load-path)))))) (cond ((eq (quote dotfile) (eieio-oref pkg (quote :owner))) (configuration-layer//activate-package pkg-name) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//activate-package pkg-name) (configuration-layer//configure-package pkg)))))
  (let ((pkg-name (eieio-oref pkg (quote :name)))) (cond ((eieio-oref pkg (quote :excluded)) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg (quote :owner))) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) (t (let ((location (eieio-oref pkg (quote :location)))) (cond ((stringp location) (if (file-directory-p location) (setq load-path ...) (spacemacs-buffer/warning "Location path for package %S does not exists (value: %s)." pkg location))) ((and (eq ... location) (eq ... ...)) (setq load-path (cons ... load-path))) ((eq (quote local) location) (let* (... ...) (setq load-path ...) (setq load-path ...))))) (cond ((eq (quote dotfile) (eieio-oref pkg (quote :owner))) (configuration-layer//activate-package pkg-name) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//activate-package pkg-name) (configuration-layer//configure-package pkg))))))
  (while --dolist-tail-- (setq pkg (car --dolist-tail--)) (spacemacs-buffer/loading-animation) (let ((pkg-name (eieio-oref pkg (quote :name)))) (cond ((eieio-oref pkg (quote :excluded)) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg (quote :owner))) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) (t (let ((location (eieio-oref pkg ...))) (cond ((stringp location) (if ... ... ...)) ((and ... ...) (setq load-path ...)) ((eq ... location) (let* ... ... ...)))) (cond ((eq (quote dotfile) (eieio-oref pkg ...)) (configuration-layer//activate-package pkg-name) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//activate-package pkg-name) (configuration-layer//configure-package pkg)))))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- packages) pkg) (while --dolist-tail-- (setq pkg (car --dolist-tail--)) (spacemacs-buffer/loading-animation) (let ((pkg-name (eieio-oref pkg (quote :name)))) (cond ((eieio-oref pkg (quote :excluded)) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg (quote :owner))) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) (t (let ((location ...)) (cond (... ...) (... ...) (... ...))) (cond ((eq ... ...) (configuration-layer//activate-package pkg-name) (spacemacs-buffer/message ...)) (t (configuration-layer//activate-package pkg-name) (configuration-layer//configure-package pkg)))))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  configuration-layer//configure-packages-2(([eieio-class-tag--cfgl-package 4clojure guanghui nil nil elpa nil nil] [eieio-class-tag--cfgl-package ac-ispell auto-completion nil nil elpa nil nil] [eieio-class-tag--cfgl-package ace-link spacemacs nil nil elpa nil nil] [eieio-class-tag--cfgl-package ace-pinyin chinese nil nil elpa nil nil] [eieio-class-tag--cfgl-package ace-window spacemacs nil (guanghui) elpa nil nil] [eieio-class-tag--cfgl-package adaptive-wrap spacemacs nil nil elpa nil nil] [eieio-class-tag--cfgl-package aggressive-indent spacemacs nil nil elpa nil nil] [eieio-class-tag--cfgl-package anaconda-mode python nil nil elpa nil nil] [eieio-class-tag--cfgl-package auto-compile emacs-lisp nil nil elpa nil nil] [eieio-class-tag--cfgl-package auto-complete auto-completion nil nil elpa nil nil] [eieio-class-tag--cfgl-package auto-dictionary spacemacs nil nil elpa nil nil] [eieio-class-tag--cfgl-package auto-highlight-symbol spacemacs nil nil elpa nil nil] [eieio-class-tag--cfgl-package auto-yasnippet auto-completion nil nil elpa nil nil] [eieio-class-tag--cfgl-package avy spacemacs nil (guanghui) elpa nil nil] [eieio-class-tag--cfgl-package bind-key spacemacs-base nil nil elpa nil nil] [eieio-class-tag--cfgl-package bookmark spacemacs-base nil nil elpa nil nil] [eieio-class-tag--cfgl-package buffer-move spacemacs nil nil elpa nil nil] [eieio-class-tag--cfgl-package cc-mode c-c++ nil (guanghui) elpa nil nil] [eieio-class-tag--cfgl-package centered-cursor spacemacs nil nil local nil nil] [eieio-class-tag--cfgl-package chinese-wbim chinese nil (guanghui) elpa nil nil] [eieio-class-tag--cfgl-package clang-format c-c++ nil nil elpa nil nil] [eieio-class-tag--cfgl-package clean-aindent-mode spacemacs nil nil elpa nil nil] [eieio-class-tag--cfgl-package cmake-font-lock zilongshanren nil nil elpa nil nil] [eieio-class-tag--cfgl-package cmake-mode c-c++ nil (zilongshanren) elpa nil nil] [eieio-class-tag--cfgl-package coffee-mode javascript nil nil elpa nil nil] [eieio-class-tag--cfgl-package company auto-completion (shell) (zilongshanren c-c++ racket emacs-lisp javascript html python org markdown) elpa nil nil] [eieio-class-tag--cfgl-package company-anaconda python nil nil elpa nil nil] [eieio-class-tag--cfgl-package company-c-headers c-c++ nil (guanghui) elpa nil nil] [eieio-class-tag--cfgl-package company-emoji emoji nil (org markdown) elpa nil nil] [eieio-class-tag--cfgl-package company-quickhelp auto-completion nil nil elpa nil nil] [eieio-class-tag--cfgl-package company-quickhelp-mode nil nil nil elpa nil nil] [eieio-class-tag--cfgl-package company-statistics auto-completion nil nil elpa nil nil] [eieio-class-tag--cfgl-package company-tern javascript nil nil elpa nil nil] [eieio-class-tag--cfgl-package company-web html nil nil elpa nil nil] [eieio-class-tag--cfgl-package company-ycmd ycmd nil (c-c++) elpa nil nil] [eieio-class-tag--cfgl-package css-mode html nil (zilongshanren) elpa nil nil] [eieio-class-tag--cfgl-package cython-mode python nil nil elpa nil nil] [eieio-class-tag--cfgl-package define-word spacemacs nil nil elpa nil t] [eieio-class-tag--cfgl-package deft nil nil nil elpa nil nil] [eieio-class-tag--cfgl-package desktop spacemacs nil nil elpa nil nil] [eieio-class-tag--cfgl-package diff-hl version-control nil (vinegar) elpa nil nil] [eieio-class-tag--cfgl-package diff-mode version-control nil nil elpa nil nil] [eieio-class-tag--cfgl-package diminish spacemacs-base nil nil elpa nil nil] [eieio-class-tag--cfgl-package disaster c-c++ nil nil elpa nil nil] [eieio-class-tag--cfgl-package discover-my-major guanghui nil nil elpa nil nil] [eieio-class-tag--cfgl-package doc-view spacemacs nil nil elpa nil nil] [eieio-class-tag--cfgl-package ediff spacemacs-base nil nil elpa nil nil] [eieio-class-tag--cfgl-package eldoc spacemacs-base nil (emacs-lisp python) elpa nil nil] [eieio-class-tag--cfgl-package electric-indent-mode spacemacs-base nil nil built-in nil nil] [eieio-class-tag--cfgl-package elfeed guanghui nil nil elpa nil nil] ...))
  configuration-layer//configure-packages(([eieio-class-tag--cfgl-package 4clojure guanghui nil nil elpa nil nil] [eieio-class-tag--cfgl-package ac-ispell auto-completion nil nil elpa nil nil] [eieio-class-tag--cfgl-package ace-link spacemacs nil nil elpa nil nil] [eieio-class-tag--cfgl-package ace-pinyin chinese nil nil elpa nil nil] [eieio-class-tag--cfgl-package ace-window spacemacs nil (guanghui) elpa nil nil] [eieio-class-tag--cfgl-package adaptive-wrap spacemacs nil nil elpa nil nil] [eieio-class-tag--cfgl-package aggressive-indent spacemacs nil nil elpa nil nil] [eieio-class-tag--cfgl-package anaconda-mode python nil nil elpa nil nil] [eieio-class-tag--cfgl-package auto-compile emacs-lisp nil nil elpa nil nil] [eieio-class-tag--cfgl-package auto-complete auto-completion nil nil elpa nil nil] [eieio-class-tag--cfgl-package auto-dictionary spacemacs nil nil elpa nil nil] [eieio-class-tag--cfgl-package auto-highlight-symbol spacemacs nil nil elpa nil nil] [eieio-class-tag--cfgl-package auto-yasnippet auto-completion nil nil elpa nil nil] [eieio-class-tag--cfgl-package avy spacemacs nil (guanghui) elpa nil nil] [eieio-class-tag--cfgl-package bind-key spacemacs-base nil nil elpa nil nil] [eieio-class-tag--cfgl-package bookmark spacemacs-base nil nil elpa nil nil] [eieio-class-tag--cfgl-package buffer-move spacemacs nil nil elpa nil nil] [eieio-class-tag--cfgl-package cc-mode c-c++ nil (guanghui) elpa nil nil] [eieio-class-tag--cfgl-package centered-cursor spacemacs nil nil local nil nil] [eieio-class-tag--cfgl-package chinese-wbim chinese nil (guanghui) elpa nil nil] [eieio-class-tag--cfgl-package clang-format c-c++ nil nil elpa nil nil] [eieio-class-tag--cfgl-package clean-aindent-mode spacemacs nil nil elpa nil nil] [eieio-class-tag--cfgl-package cmake-font-lock zilongshanren nil nil elpa nil nil] [eieio-class-tag--cfgl-package cmake-mode c-c++ nil (zilongshanren) elpa nil nil] [eieio-class-tag--cfgl-package coffee-mode javascript nil nil elpa nil nil] [eieio-class-tag--cfgl-package company auto-completion (shell) (zilongshanren c-c++ racket emacs-lisp javascript html python org markdown) elpa nil nil] [eieio-class-tag--cfgl-package company-anaconda python nil nil elpa nil nil] [eieio-class-tag--cfgl-package company-c-headers c-c++ nil (guanghui) elpa nil nil] [eieio-class-tag--cfgl-package company-emoji emoji nil (org markdown) elpa nil nil] [eieio-class-tag--cfgl-package company-quickhelp auto-completion nil nil elpa nil nil] [eieio-class-tag--cfgl-package company-quickhelp-mode nil nil nil elpa nil nil] [eieio-class-tag--cfgl-package company-statistics auto-completion nil nil elpa nil nil] [eieio-class-tag--cfgl-package company-tern javascript nil nil elpa nil nil] [eieio-class-tag--cfgl-package company-web html nil nil elpa nil nil] [eieio-class-tag--cfgl-package company-ycmd ycmd nil (c-c++) elpa nil nil] [eieio-class-tag--cfgl-package css-mode html nil (zilongshanren) elpa nil nil] [eieio-class-tag--cfgl-package cython-mode python nil nil elpa nil nil] [eieio-class-tag--cfgl-package define-word spacemacs nil nil elpa nil t] [eieio-class-tag--cfgl-package deft nil nil nil elpa nil nil] [eieio-class-tag--cfgl-package desktop spacemacs nil nil elpa nil nil] [eieio-class-tag--cfgl-package diff-hl version-control nil (vinegar) elpa nil nil] [eieio-class-tag--cfgl-package diff-mode version-control nil nil elpa nil nil] [eieio-class-tag--cfgl-package diminish spacemacs-base nil nil elpa nil nil] [eieio-class-tag--cfgl-package disaster c-c++ nil nil elpa nil nil] [eieio-class-tag--cfgl-package discover-my-major guanghui nil nil elpa nil nil] [eieio-class-tag--cfgl-package doc-view spacemacs nil nil elpa nil nil] [eieio-class-tag--cfgl-package ediff spacemacs-base nil nil elpa nil nil] [eieio-class-tag--cfgl-package eldoc spacemacs-base nil (emacs-lisp python) elpa nil nil] [eieio-class-tag--cfgl-package electric-indent-mode spacemacs-base nil nil built-in nil nil] [eieio-class-tag--cfgl-package elfeed guanghui nil nil elpa nil nil] ...))
  configuration-layer//load-packages(([eieio-class-tag--cfgl-package 4clojure guanghui nil nil elpa nil nil] [eieio-class-tag--cfgl-package ac-ispell auto-completion nil nil elpa nil nil] [eieio-class-tag--cfgl-package ace-link spacemacs nil nil elpa nil nil] [eieio-class-tag--cfgl-package ace-pinyin chinese nil nil elpa nil nil] [eieio-class-tag--cfgl-package ace-window spacemacs nil (guanghui) elpa nil nil] [eieio-class-tag--cfgl-package adaptive-wrap spacemacs nil nil elpa nil nil] [eieio-class-tag--cfgl-package aggressive-indent spacemacs nil nil elpa nil nil] [eieio-class-tag--cfgl-package anaconda-mode python nil nil elpa nil nil] [eieio-class-tag--cfgl-package auto-compile emacs-lisp nil nil elpa nil nil] [eieio-class-tag--cfgl-package auto-complete auto-completion nil nil elpa nil nil] [eieio-class-tag--cfgl-package auto-dictionary spacemacs nil nil elpa nil nil] [eieio-class-tag--cfgl-package auto-highlight-symbol spacemacs nil nil elpa nil nil] [eieio-class-tag--cfgl-package auto-yasnippet auto-completion nil nil elpa nil nil] [eieio-class-tag--cfgl-package avy spacemacs nil (guanghui) elpa nil nil] [eieio-class-tag--cfgl-package bind-key spacemacs-base nil nil elpa nil nil] [eieio-class-tag--cfgl-package bookmark spacemacs-base nil nil elpa nil nil] [eieio-class-tag--cfgl-package buffer-move spacemacs nil nil elpa nil nil] [eieio-class-tag--cfgl-package cc-mode c-c++ nil (guanghui) elpa nil nil] [eieio-class-tag--cfgl-package centered-cursor spacemacs nil nil local nil nil] [eieio-class-tag--cfgl-package chinese-wbim chinese nil (guanghui) elpa nil nil] [eieio-class-tag--cfgl-package clang-format c-c++ nil nil elpa nil nil] [eieio-class-tag--cfgl-package clean-aindent-mode spacemacs nil nil elpa nil nil] [eieio-class-tag--cfgl-package cmake-font-lock zilongshanren nil nil elpa nil nil] [eieio-class-tag--cfgl-package cmake-mode c-c++ nil (zilongshanren) elpa nil nil] [eieio-class-tag--cfgl-package coffee-mode javascript nil nil elpa nil nil] [eieio-class-tag--cfgl-package company auto-completion (shell) (zilongshanren c-c++ racket emacs-lisp javascript html python org markdown) elpa nil nil] [eieio-class-tag--cfgl-package company-anaconda python nil nil elpa nil nil] [eieio-class-tag--cfgl-package company-c-headers c-c++ nil (guanghui) elpa nil nil] [eieio-class-tag--cfgl-package company-emoji emoji nil (org markdown) elpa nil nil] [eieio-class-tag--cfgl-package company-quickhelp auto-completion nil nil elpa nil nil] [eieio-class-tag--cfgl-package company-quickhelp-mode nil nil nil elpa nil nil] [eieio-class-tag--cfgl-package company-statistics auto-completion nil nil elpa nil nil] [eieio-class-tag--cfgl-package company-tern javascript nil nil elpa nil nil] [eieio-class-tag--cfgl-package company-web html nil nil elpa nil nil] [eieio-class-tag--cfgl-package company-ycmd ycmd nil (c-c++) elpa nil nil] [eieio-class-tag--cfgl-package css-mode html nil (zilongshanren) elpa nil nil] [eieio-class-tag--cfgl-package cython-mode python nil nil elpa nil nil] [eieio-class-tag--cfgl-package define-word spacemacs nil nil elpa nil t] [eieio-class-tag--cfgl-package deft nil nil nil elpa nil nil] [eieio-class-tag--cfgl-package desktop spacemacs nil nil elpa nil nil] [eieio-class-tag--cfgl-package diff-hl version-control nil (vinegar) elpa nil nil] [eieio-class-tag--cfgl-package diff-mode version-control nil nil elpa nil nil] [eieio-class-tag--cfgl-package diminish spacemacs-base nil nil elpa nil nil] [eieio-class-tag--cfgl-package disaster c-c++ nil nil elpa nil nil] [eieio-class-tag--cfgl-package discover-my-major guanghui nil nil elpa nil nil] [eieio-class-tag--cfgl-package doc-view spacemacs nil nil elpa nil nil] [eieio-class-tag--cfgl-package ediff spacemacs-base nil nil elpa nil nil] [eieio-class-tag--cfgl-package eldoc spacemacs-base nil (emacs-lisp python) elpa nil nil] [eieio-class-tag--cfgl-package electric-indent-mode spacemacs-base nil nil built-in nil nil] [eieio-class-tag--cfgl-package elfeed guanghui nil nil elpa nil nil] ...))
  configuration-layer/sync()
  (progn (load-file (concat user-emacs-directory "core/core-load-paths.el")) (if init-file-debug (progn (require (quote core-debug)))) (require (quote core-spacemacs)) (require (quote core-configuration-layer)) (spacemacs/init) (spacemacs/maybe-install-dotfile) (configuration-layer/sync) (spacemacs/setup-startup-hook) (require (quote server)) (if (server-running-p) nil (server-start)))
  (if (spacemacs/emacs-version-ok) (progn (load-file (concat user-emacs-directory "core/core-load-paths.el")) (if init-file-debug (progn (require (quote core-debug)))) (require (quote core-spacemacs)) (require (quote core-configuration-layer)) (spacemacs/init) (spacemacs/maybe-install-dotfile) (configuration-layer/sync) (spacemacs/setup-startup-hook) (require (quote server)) (if (server-running-p) nil (server-start))))
  eval-buffer(#<buffer  *load*> nil "d:/Program Files/emacs-25.5/home/.emacs.d/init.el" nil t)  ; Reading at buffer position 1084
  load-with-code-conversion("d:/Program Files/emacs-25.5/home/.emacs.d/init.el" "d:/Program Files/emacs-25.5/home/.emacs.d/init.el" t t)
  load("d:/Program Files/emacs-25.5/home/.emacs.d/init" t t)
  #[0 "\205\266

**Comment by wzhe** [comment]
安装过程中有好多包显示an error occur 。。好像再启动的话也不会去检查以前的包到底装好了没。。这个有什么好办法可以快速定位哪些包安装时没装好么

**Comment by zilongshanren** [comment]
@wzhe  可以先注释掉一些 layer 或者 package，然后再看看有问题没有。
类似二分查找法比较有效。

**Comment by zilongshanren** [comment]
@wzhe  更新一下我的新配置可以解决 org-mode-map 找不到的错误 。
然后org-babel-header-args-safe-fn 找不到，可以通过 `SPC h L` 找到`ob-R.el`，然后对此文件执行`byte-compile-file`后再重启就可以了，这是 org-mode 的一个 bug。

**Comment by zilongshanren** [comment]
@wzhe  有些显示 错误 可能是网络问题，可以通过打开 shadowsocks，然后用`SPC o t s`打开 shadowsocks 代码，再执行`SPC f e R`来更新完所有的 package。完了后重启 Emacs 即可。

**Comment by wzhe** [comment]
@zilongshanren 我更新你的配置后，先把所有的包全删除了，然后挂代理，更新完所有的package，然后就没error了。但是现在还有几个waring，每次打开时都会弹出来，比较烦，有什么办法能去除么。
![qq 20151028200200](https://cloud.githubusercontent.com/assets/6120110/10787958/2f061c86-7daf-11e5-9fe2-a8a21678cccb.png)

**Comment by zilongshanren** [comment]
@wzhe  这个 warning 在 Mac 下面没有哦。 能否告知此 buffer 的 名字和 major mode?

**Comment by zilongshanren** [comment]
@wzhe 
试试在.spacemacs.d/init.el 里面的 user-config 函数里面添加 `(setq byte-compile-warnings  nil)` 
看看能否解决问题。

**Comment by wzhe** [comment]
我也不知道这几个是在那用到的。buff名是complie log
 这个句话好像没起做用(setq byte-compile-warnings nil)
![qq 20151028205008](https://cloud.githubusercontent.com/assets/6120110/10788929/893665fc-7db5-11e5-927d-01febfccd0d1.png)

**Comment by zilongshanren** [comment]
@wzhe 这个问题不大，先无视吧。如果知道buffer 名字，可以写一个 hook 在 Emacs 启动后自动 kill 掉此 buffer.
