### ISSUE TITLE
spacemacs 中 vim 模式可以使用其他的 vim 插件吗？

### ISSUE THREAD

**Issue by xiaoDC** [zilongshanren/spacemacs-private#71]
@zilongshanren 我也是之前 vim 党转过来的，想问一下 spacemacs 能使用类似 https://github.com/kshenoy/vim-signature 的插件吗？ 需要怎么配置？

**Comment by zilongshanren** [comment]
spacemacs 肯定是不能直接使用 vim 的插件的，你可以去搜索对应的 evil 替代插件。

**Comment by xiaoDC** [comment]
@zilongshanren  好的，谢谢！
