### ISSUE TITLE
项目切换

### ISSUE THREAD

**Issue by gentoolovers** [zilongshanren/spacemacs-private#75]
山人，我用spc p p 切换项目后，spc  p f的时候不会切换到项目目录啊，要怎么切换过去啊？

**Comment by xcodebuild** [comment]
什么叫 **不会切换到项目目录** ，提示 `not in project`?

**Comment by gentoolovers** [comment]
就是 打开的还是当前目录，不在项目的目录。

**Comment by xcodebuild** [comment]
试了下没能重现这个问题。。 `SPC pp` 选择一个项目，然后选择一个文件。 `SPC pf` 工作正常。

**Comment by gentoolovers** [comment]
可能是我emacs 版本太低了吧，我去换个高点的试试
