### ISSUE TITLE
修改dotspacemacs-additional-packages无法安装新的package

### ISSUE THREAD

**Issue by dorado-lmz** [zilongshanren/spacemacs-private#76]
在`dotfile`中加入`dotspacemacs-additional-packages '(racket-mode)`
然后按照 `package-install racket-mode`
重启**emacs**后，
`orphan delete ...`
把**racket-mode**自动删除了

---

emacs 25.1
os: mac

**Comment by zilongshanren** [comment]
@dorado-lmz  
直接添加 racket layer 试试？

**Comment by dorado-lmz** [comment]
ok,看了你的"21天学emacs"的day13就懂了，谢谢！
