### ISSUE TITLE
关于 mac 安装

### ISSUE THREAD

**Issue by mccheung** [zilongshanren/spacemacs-private#78]
hi,  
按照文档提示(osx 10.11.6)： 

`brew tap railwaycat/emacsmacport;
brew install emacs-mac --with-spacemacs-icon --HEAD --with-gnutls
`

这样安装 emacs 在启动的时候会报错：

`Symbol's function definition is void: define-fringe-bitmap`

需要加上 --with-cocoa 才行

`brew install emacs --with-cocoa`

**Comment by zilongshanren** [comment]
@mccheung  我这边好像并不会哦。。  你是使用我的 emacs 配置启动报错的吗？

**Comment by ghost** [comment]
osx 10.12.4，不知道为什么，不论我是`brew cask install emacs`还是`brew install emacs-mac`，git clone 后打开都不是spacemacs，any idea?
