### ISSUE TITLE
是否把 elpa 目录 push上来

### ISSUE THREAD

**Issue by zilongshanren** [zilongshanren/spacemacs-private#8]
这样的话，直接 clone 就可以用了，不用下载 package，而且也不用管版本依赖的问题。

**Comment by wzhe** [comment]
对于不修改配置的人来说，这是非常好的。
但如果经常更改配置文件，配置文件改变了的话，启动时会自动去删除一些包，然后下次配置时又会去下载package。
建议把elpa目录另开一个仓库，然后建议大家去clone，提醒大家每次更新配置时同步去更新下elpa目录。让大家根据自己的网络环境、懒惰程度等，去选择要不要clone。

**Comment by zilongshanren** [comment]
@wzhe 如果再维护一个 elpa 仓库 ，那肯定 是要跟我的配置进行同步 的，所以不会出现 你说的自动删除 包的情况，不过这样要用 submodule 进行管理，想想还是挺麻烦的

**Comment by wzhe** [comment]
@zilongshanren 哈哈，那这个事就先放一放，等确实有人需要clone时，再拿出来考虑考虑。那时再开始维护也不迟。
PS：你的配置和视频都很赞！
