### ISSUE TITLE
(Searching for program No such file or directory ispell) mwheel-scroll: End of buffer e

### ISSUE THREAD

**Issue by talzxia** [zilongshanren/spacemacs-private#80]
(Searching for program No such file or directory ispell)
mwheel-scroll: End of buffer
e

**Comment by zilongshanren** [comment]
你需要安装 ispell

**Comment by talzxia** [comment]
你在init.el中排除了ispell,我修改后，新建了一个snippets目录，仍出现以下信息：
Starting new Ispell process ispell with default dictionary...
Error enabling Flyspell mode:
(Searching for program No such file or directory ispell)
Starting new Ispell process ispell with default dictionary...
E

**Comment by zilongshanren** [comment]
http://unix.stackexchange.com/questions/38916/how-do-i-configure-emacs-to-use-ispell-on-mac-os-x
