### ISSUE TITLE
js2-mode indent 问题

### ISSUE THREAD

**Issue by xiaoDC** [zilongshanren/spacemacs-private#82]
子龙您好，我在用js2-mode时，如下代码 return 返回时，`DOM.p()` 的缩进有问题

`import React, { Component, createFactory, PropTypes } from 'react';
import classname from 'classnames';
import Input from '../input';

const input = createFactory(Input);

class SearchInput extends Component {
  render() {
    const { className } = this.props;
    const cls = classname({
      'search-input-wrapper': true,
    });

```
return DOM.div({
  className: cls,
},
               DOM.p(),
  input()
);
```

  }
}

export default SearchInput;

只有在我用写类似 
`DOM.div({},`
`****)`
***\* 的缩进就出现问题，困扰了我很久，希望您能指点指点！

**Comment by zilongshanren** [comment]
换种方式写貌似可以缩进正确：

``` js
import React, { Component, createFactory, PropTypes } from 'react';
import classname from 'classnames';
import Input from '../input';

const input = createFactory(Input);

class SearchInput extends Component {
    render() {
        const { className } = this.props;
        const cls = classname({
            'search-input-wrapper': true,
        });

        return DOM.div(
            {
                className: cls,
            },
            DOM.p(),
            input()
        );
    }
}

export default SearchInput;

```
