### ISSUE TITLE
helm-swoop搜索问题

### ISSUE THREAD

**Issue by jinghongjun** [zilongshanren/spacemacs-private#83]
helm-swoop搜索问题，如果要批量修改，快捷键是什么？

**Comment by zilongshanren** [comment]
@jinghongjun  我现在已经没有用 Helm-swoop 了，指修改的话，一般是使用 helm-ag 吧，在使用 helm-ag 搜索完成之后，按 `C-c C-e` 来进行批量修改。

**Comment by jinghongjun** [comment]
C-c C-e: counsle-git-grep-query-replace 
C-c C-o: ivy-occur
我应该进入ivy-occur，之后用什么快捷键进行批量更改？

**Comment by zilongshanren** [comment]
@jinghongjun 

`C-x C-q` 修改完成后用 `C-c C-c`确认

**Comment by jinghongjun** [comment]
估计ｍａｃ上用的spacemcs和ubuntu上用的spacemacs快捷键不一致。
