### ISSUE TITLE
怎么设置光标在insert模式下是i-bean 而不是block

### ISSUE THREAD

**Issue by turengege** [zilongshanren/spacemacs-private#84]
不好意思这种问题应该自己去研究的，但是之前没有接触过emac和lisp，上手有点困难
希望帮我指出在哪个文件里面配置这个

**Comment by zilongshanren** [comment]
`(setq evil-insert-state-cursor '("chartreuse3" (bar . 2)))`

**Comment by turengege** [comment]
解决了 thanks
