### ISSUE TITLE
怎么切换输入法

### ISSUE THREAD

**Issue by turengege** [zilongshanren/spacemacs-private#85]
我的快捷键是super + space
按了后 显示s-spc is undefined

**Comment by zilongshanren** [comment]
你是不是让 Emacs 吃掉系统的快捷键了？我这边并没有这个问题。。。

**Comment by turengege** [comment]
我自己没有配置其他东西， 系统是ubuntu16.04 ,输入法用的sogou

**Comment by turengege** [comment]
解决了 用了emacs自带的输入法
