### ISSUE TITLE
关于正则

### ISSUE THREAD

**Issue by turengege** [zilongshanren/spacemacs-private#87]
/\d+ （查找数字）没起作用
查了下emacs的正则的确不太一样，请问能用vim的正则么，

**Comment by zilongshanren** [comment]
暂时不可以，可以使用 `pcre-to-elisp` 来转换 elisp 的正则到 perl 的正则，可能跟 vim 的正则是一样的。

**Comment by turengege** [comment]
thank you 用pcre 就舒服多了

**Comment by turengege** [comment]
我想默认开启pcre-mode , 在better-default/config.el 中加了一行
`(pcre-mode)`
这样启动后，报错 void function:pcre-mode
但是我在config.el 中按C-x C-e 执行是可以启动pcre-mode

**Comment by zilongshanren** [comment]
你不能加在 config 里面，可以加在 packages.el 里面

**Comment by turengege** [comment]
还是不行 ，void function

**Comment by zilongshanren** [comment]
要么你就写到 `user-config`函数里面吧，或者写在 post-init-pcre-mode 里面

**Comment by turengege** [comment]
那样也不行 一样的错误 应该是加载顺序问题， 现在作为hook是可以了。 还有个问题， 我现在js文件进去后majormode默认是JavascripteIde 我想改成js2-mode，怎么改了

**Comment by zilongshanren** [comment]
http://book.emacs-china.org/#orgheadline11

**Comment by turengege** [comment]
试了下不行。auto-mode-alist里面有两个关于.js的定义，而我不管把js2-mode放前面还是放后面貌似都不行。
后来自己写个个函数替换了本来的javascript-mode 可以了

```
(defun set-auto-mode-alist (auto-mode-cel) (
      let ((auto-mode-set-key (car auto-mode-cel)))
       (setq auto-mode-alist
             (mapcar
              (lambda (one-auto-mode-cel)
                (if (string= auto-mode-set-key (car one-auto-mode-cel))
                    auto-mode-cel
                  one-auto-mode-cel
                  ))
              auto-mode-alist))))

(set-auto-mode-alist '("\\.js\\'" . js2-mode))

```

**Comment by turengege** [comment]
我2了 ，这个alist本身可以set
