### ISSUE TITLE
org-mode导出pdf是没有反应

### ISSUE THREAD

**Issue by scloudyy** [zilongshanren/spacemacs-private#9]
山人你好，将org导出为pdf时*Message*里显示
“Wrote /root/org-notes/gtd.tex
Processing LaTeX file ./gtd.tex...
(Shell command succeeded with no output)
org-latex-compile: PDF file ./gtd.pdf wasn't produced”
然后并没有导出，我是linux系统装了texlive，然后按照你配置里导出中文pdf注释里的网站http://freizl.github.io/posts/tech/2012-04-06-export-orgmode-file-in-Chinese.html  （作者已经改了博客结构，直接按着个网址站不到文章的，现在是 http://freizl.github.io/posts/2012-04-06-export-orgmode-file-in-Chinese.html 这个网址）装了latex-cjk-chinese，texlive-xetex，在org开头也加了
#+LaTeX_HEADER: \usepackage{CJK}
#+LaTeX_HEADER: \begin{CJK}{UTF8}{gbsn}
然而还是导不出pdf，google了半天也不能解决，所以特来请教该如何将org导出为pdf，如果有时间的话请讲的详细点，万分感谢！

**Comment by zilongshanren** [comment]
@scloudyy 
你的/root/org-notes/gtd.org这个文件存在吗？

**Comment by zilongshanren** [comment]
@scloudyy  如果要导出中文pdf的话，需要在org文件开头添加一些内容。

```
#+LATEX_HEADER: \usepackage{xltxtra}
#+LATEX_HEADER: \setmainfont{FangSong}
#+LATEX_HEADER: \usepackage{seqsplit}
#+OPTIONS: TeX:t LaTeX:t skip:nil d:nil tasks:nil pri:nil title:t
```
