### ISSUE TITLE
搜索问题

### ISSUE THREAD

**Issue by jinghongjun** [zilongshanren/spacemacs-private#91]
使用搜索时，spacemacs用不用建立相关的搜索索引？有的文件或字符串，使用spacemacs并没有搜索出来，当使用相关的命令是可以搜索出来的(find ./ -name '*.sh' | xargs grep -rn 'global')

**Comment by zilongshanren** [comment]
我用的是 ag 来搜索，这个是不需要建立索引的。没有搜索出来，可能的原因就是被 ag 忽略掉了。比如这个文件是在.gitignore 里面。
