### ISSUE TITLE
Error (use-package):helm-gtags:init:Symbol's value as variable is void:spacemacs-jump-handlers-tcl-mode

### ISSUE THREAD

**Issue by lzjqsdd** [zilongshanren/spacemacs-private#92]
添加你的配置后出现，Error (use-package):helm-gtags:init:Symbol's value as variable is void:spacemacs-jump-handlers-tcl-mode

直接使用spacemacs没有安装报错。
我的环境：
ubuntu14.04
emacs 24.5.1

**Comment by zilongshanren** [comment]
@lzjqsdd  Spacemacs develop 分支最新的 commit 有问题，https://github.com/syl20bnr/spacemacs/commit/9066d073b2e46715b8ecd855b96399a33495bff1

你要么往回 revert  4 个 commit，要么等作者fix，也可以自己发个 PR 过去。

**Comment by lzjqsdd** [comment]
恩恩，谢谢，revert下版本试了可以了，刚开始接触emacs还不太了解整个的机制
