### ISSUE TITLE
smart-parent 和 hungry-delete的冲突

### ISSUE THREAD

**Issue by ghost** [zilongshanren/spacemacs-private#93]
你好， 具体请看着个issue ：https://github.com/syl20bnr/spacemacs/issues/6584
这个问题解决后还有一个问题：在emacs-lisp-mode下当光标在pair里面（以  "|" 为例），我再次按下 " 时光标应该跳出" 而不是插入"" .

**Comment by zilongshanren** [comment]
因为我使用了 lispy，貌似并没有冲突。。。

**Comment by ghost** [comment]
哦, 我这出现了冲突, 不过那个issue面提供了解决方法, 解决了. 谢谢^_^
