### ISSUE TITLE
exec-path 与 shell $PATH 不一致

### ISSUE THREAD

**Issue by ghost** [zilongshanren/spacemacs-private#94]
<img width="668" alt="screen shot 2016-09-08 at 12 26 37 pm" src="https://cloud.githubusercontent.com/assets/11426875/18337023/8a5731d4-75bf-11e6-8978-f5c3f99eb47d.png">

我不知道为什么exec-path为什么会和我shell的PATH不一致, 我有用正确exec-path-from-shell这个插件.

**Comment by zilongshanren** [comment]
I found there are difference between exec-path and PATH.

The value of environment variable “PATH” is used by emacs when you are running a shell in emacs, similar to when you are using a shell in a terminal.
The exec-path is used by emacs itself to find programs it needs for its features, such as spell checking, file compression, compiling, grep, diff, etc. Original from http://ergoemacs.org/emacs/emacs_env_var_paths.html

**Comment by ghost** [comment]
谢谢^_^ , 这个我看了, 我想要的效果是同步exec-path和我shell PATH,又不想手动去(add-to-list 'exec-path '(path1 path2 ....)). 你能输出一下你的exec-path看下么? 貌似我用spacemacs的裸配emacs的exec-path和我的shell PATH 是一致的
ps : 我有运行: exec-path-from-shell后emacs 的 exec-path 还是和我的shell PATH不一致.

**Comment by zilongshanren** [comment]
@vimniky

这个是我的 `exec-path`:

```
("/usr/local/bin/" "/usr/bin/" "/bin/" "/usr/sbin/" "/sbin/" "/opt/X11/bin/" "/opt/ImageMagick/bin/" "/Library/TeX/texbin/" "/Users/guanghui/cocos2d-x/templates/" "/Users/guanghui/cocos2d-x/" "/Users/guanghui/.cask/bin/" "/Users/guanghui/.cabal/bin/" "/Users/guanghui/AndroidDev/adt-bundle-mac-x86_64-20130522/sdk/tools/" "/Users/guanghui/AndroidDev/adt-bundle-mac-x86_64-20130522/sdk/platform-tools/" "/Users/guanghui/AndroidDev/adt-bundle-mac-x86_64-20130522/sdk/sdk/platform-tools/" "/Users/guanghui/AndroidDev/android-ndk-r12b/" "/Applications/Cocos/tools/ant/bin/" "/Users/guanghui/workspace/golang/bin/" "/Applications/Racket v6.1.1/bin/" "/usr/local/Cellar/emacs-mac/HEAD/libexec/emacs/25.1/x86_64-apple-darwin15.6.0/")

```

**Comment by ghost** [comment]
恩, 你的exec-path和你的shell PATH是一至的, 我这不一致,出问题了,还不知道怎么回事,我也没改什么东西. 谢谢^_^

**Comment by cranehuang** [comment]
@vimniky   我也遇到了和你一样的问题，Spacemacs的PATH和shell中的PATH不一致，后来在Spacemacs官网FAQ看到了相关说明。以zsh为例，把你的PATH配置放一份到.zshenv  就好了。
<img width="775" alt="14768771-d83e-488e-9f9f-185384cd6be4" src="https://cloud.githubusercontent.com/assets/5162826/20638188/0101e628-b3da-11e6-9dc8-dc3885b6bdd5.png">
