### ISSUE TITLE
open-file-with-projectile-or-counsel-git  中文乱码

### ISSUE THREAD

**Issue by mydearxym** [zilongshanren/spacemacs-private#95]
使用 [open-file-with-projectile-or-counsel-git](https://github.com/zilongshanren/spacemacs-private/blob/develop/layers/zilongshanren-misc/funcs.el#L225) 函数打开含有中文文件的目录时，中文文件名显示为乱码。

![image](https://cloud.githubusercontent.com/assets/6184465/18411722/ede61fc0-77af-11e6-93c6-10954d4652b1.png)

**Comment by jadestrong** [comment]
同求解答，find-file-in-project没有这问题，但是对于md文件却检索不出来，只能查找那些html、css、js等文件

**Comment by zilongshanren** [comment]
@jadestrong @mydearxym  我那个命令默认是使用 counsel-git 去搜索文件的，你们可以把按键绑定改掉。

**Comment by zilongshanren** [comment]
@mydearxym @jadestrong  更新我的最新版本，这个问题解决了。
