### ISSUE TITLE
安装完成显示有一项错误

### ISSUE THREAD

**Issue by ILove-11** [zilongshanren/spacemacs-private#97]
安装完成以后
启动 emacs 显示有一项错误
如下所示：

Error in dotspacemacs/user-config: Wrong number of arguments: (lambda (mode unicode &optional ascii) "Diminish MODE name in mode line to UNICODE or ASCII depending on the value

`dotspacemacs-mode-line-unicode-symbols'.

If ASCII si not provided then UNICODE is used instead." (list (quote add-to-list) (quote (quote spacemacs--diminished-minor-modes)) (list (quote quote) (list mode unicode ascii)))), 1

**Comment by zilongshanren** [comment]
你是什么系统？ emacs 什么版本？

**Comment by ILove-11** [comment]
系统 macOS Sierra
emacs 版本 24.5

**Comment by tsimaa** [comment]
我的也是。
arch linux
emacs 25.1

**Comment by zilongshanren** [comment]
@ILove-11  建议升级到 25.1 再试试，另外 spacemacs 版本建议用 develop 分支。
