### ISSUE TITLE
关于custom.el

### ISSUE THREAD

**Issue by yangjiedage** [zilongshanren/spacemacs-private#99]
custom文件是配置什么的？它里面的package-selected-packages是不是和init中的dotspacemacs-additional-packages作用一样？

**Comment by zilongshanren** [comment]
custom.el 文件是 Emacs自动生成的，它里面的 `package-selected-packages` 是 packages.el 包生成的，和 dotspacemacs-additional-packages 是完全不一样的。

你可以用 `c-h v` 查看它们的区别。
